-- ============================================================
-- Ratcopter: Sewer Race
-- Two side-by-side lanes (you on the left, an AI companion on the
-- right with horizontally-flipped artwork). Neither lane spawns pipes on
-- its own: every pipe on your screen was earned by the AI collecting a
-- coin, and every pipe on the AI's screen was earned by you.
-- The match is 5 rounds; whoever has the higher accumulated
-- score after round 5 wins.
-- ============================================================

-- Everything below runs inside main(), deferred by one frame via
-- timer.performWithDelay(1, main) at the bottom of this file. On HTML5,
-- display.actualContentWidth/Height (and screenOriginX/Y) can still reflect
-- a transient pre-layout value on the very first frame the Lua chunk
-- executes, before the browser/canvas has settled on its final size; a
-- Solar2D forum PSA on zoomEven + HTML5 resize specifically flags this.
-- Building the whole layout one frame later reads the settled values
-- instead, so the game actually fills the real window instead of being
-- shrink-wrapped to whatever size was reported a frame too early.
local function main()

math.randomseed(os.time())

-- ---------- Theme data ----------
-- Pipes are drawn as two jaws rather than one image with a hole in it, so
-- the opening between them can be moved while the pipe is in flight -- which
-- is what a clamp pipe does. These are the art stems; the file for one jaw is
-- jaw_<skin>_<shape>.png, all 16 of them generated by
-- tools/make_pipe_shapes.py from the four whole-pipe images that used to be
-- drawn directly (those are kept as that script's source art).
local pipeSkinSets = {
  sewer = { "pipe_rusty", "pipe_concrete", "pipe_mossy" },
  surface = { "pipe" },
}
local THEMES = {
  { key = "sewer", label = "SEWER", background = "Assets/ground_sewer.png", land = "Assets/land_sewer.png" },
  { key = "surface", label = "SURFACE", background = "Assets/ground.png", land = "Assets/land.png" },
}
local currentThemeIndex = 1

local function getCurrentTheme()
  return THEMES[currentThemeIndex]
end

local function randomPipeSkin()
  local skins = pipeSkinSets[getCurrentTheme().key]
  return skins[math.random(#skins)]
end

local function jawImage(skin, shape)
  return "Assets/jaw_" .. skin .. "_" .. shape .. ".png"
end

-- ---------- Sounds ----------
local dieSound, hitSound, pointSound, swooshingSound, wingSound, boomSound

-- The coin-launch sound gets a channel to itself. Every other audio.play in
-- this file auto-allocates a channel, and reserving channel 1 keeps those
-- allocations away from it -- which buys two things: the softer volume set
-- here applies to the coin alone instead of bleeding into the flap/point/hit
-- effects, and every pickup can retrigger this one channel so the sound
-- repeats on each coin earned rather than the second one landing on top of
-- a copy still playing.
local COIN_SOUND_CHANNEL = 1
local COIN_SOUND_VOLUME = 0.3 -- against 1.0 for everything else

local function loadSounds()
  dieSound = audio.loadSound("Sounds/sfx_die.caf")
  hitSound = audio.loadSound("Sounds/sfx_hit.caf")
  pointSound = audio.loadSound("Sounds/sfx_point.aif")
  swooshingSound = audio.loadSound("Sounds/sfx_swooshing.caf")
  wingSound = audio.loadSound("Sounds/sfx_wing.caf")
  boomSound = audio.loadSound("Sounds/sfx_boom.mp3")

  audio.reserveChannels(COIN_SOUND_CHANNEL)
  audio.setVolume(COIN_SOUND_VOLUME, { channel = COIN_SOUND_CHANNEL })
end

-- Plays the coin-launch sound, restarting it if it's still going. audio.play
-- on a busy channel is refused rather than queued, so without the stop a coin
-- earned while the previous one is still sounding would be silent -- and at
-- the current spawn rate two pickups inside one sound's length is common.
local function playCoinSound()
  audio.stop(COIN_SOUND_CHANNEL)
  audio.play(boomSound, { channel = COIN_SOUND_CHANNEL })
end

-- ---------- Constants (one lane's local coordinate space, 0..LANE_W) ----------
-- The content canvas is 960x540 (16:9); each lane is half that width.
-- Horizontal metrics scale relative to the original 320-wide single-lane
-- design; vertical metrics (gap size, gravity, ground/ceiling) are left
-- alone since they're already computed from the actual canvas height.
--
-- Under "letterbox" scaling, actualContentWidth/Height can exceed the
-- configured 960x540 when the device/browser aspect doesn't match 16:9
-- exactly -- and when that happens, the true visible top-left corner sits
-- at (screenOriginX, screenOriginY), which is negative, NOT (0,0). Every
-- screen position in this file is anchored off SCREEN_LEFT/SCREEN_TOP
-- instead of assuming (0,0) is the corner, so the whole layout stays
-- pinned to the actual visible edges instead of drifting off them.
local SCREEN_LEFT = display.screenOriginX
local SCREEN_TOP = display.screenOriginY
local LANE_GAP = 28
local LANE_W = (display.actualContentWidth - LANE_GAP) / 2
local LANE_SCALE = LANE_W / 320
local LANE_H = display.actualContentHeight

-- Shared with the land strip's own height in buildLaneVisuals (which the
-- land art is built from too), so GROUND_LIMIT can be pinned to a specific
-- depth into that strip instead of a magic number that could drift out of
-- sync with where the ground actually is drawn.
local LAND_HEIGHT_FRACTION = 0.19
local LAND_TOP = LANE_H * (1 - LAND_HEIGHT_FRACTION) -- where the ground art's top edge sits

-- Death triggers halfway down into the ground art rather than right at its
-- surface, so the bird visibly sinks partway into the dirt before losing
-- instead of stopping dead the instant it touches the top edge.
local GROUND_LIMIT = LAND_TOP + (LANE_H - LAND_TOP) / 2
local CEIL_LIMIT = LANE_H * 0.1
local GRAVITY = 1500
local FLAP_VY = -430
local SCROLL_SPEED = 108 * LANE_SCALE
local PIPE_SPACING = 190 * LANE_SCALE
local PIPE_HALF_W = 32 * LANE_SCALE -- 20% narrower than the original 40

-- ---------- Pipe jaw geometry ----------
-- These mirror constants of the same name in tools/make_pipe_shapes.py. They
-- describe art that is already generated, so changing one here without
-- re-running that script puts the hitbox out of step with the picture --
-- unlike the gameSetting.csv values further down, which are read fresh every
-- launch and are safe to tune on their own.
--
-- They are one table rather than three bare locals on purpose: every line of
-- this file lives inside main(), and Lua allows a single function only 200
-- locals. The settings tables further down are grouped for the same reason.
local JAW = {
  -- How tall each jaw image is drawn. It has to outrun the lane from any gap
  -- height (the furthest a jaw ever reaches is about 470px), with room to
  -- spare for a clamp closing on top of that.
  h = 560,
  -- How far past the flat gap edge a shaped tip reaches at its deepest.
  notch = 20,
  -- The pipe art only paints the middle 63% of its own width -- the rest is
  -- transparent margin, and has been since these images were first drawn.
  -- Shape profiles run across that painted body rather than the full hitbox,
  -- so a triangle tapers to a point at the edge of the pipe you can see.
  artHalf = 0.63,
}

-- Shapes, and how deeply each bites into the opening as a fraction of
-- JAW.notch. The wider the tight stretch a shape creates, the shallower it is
-- allowed to bite: a triangle pinches only at the exact centre so it can take
-- the full notch, while a pentagon holds its tight band across the middle 45%
-- and would be brutal at the same depth. Teeth are three small triangles
-- side by side: no deeper than a triangle's point, just three of them to line
-- up with, so they give up a little depth for it.
--
-- Triangle and half-moon tips used to be in this list too. They are ground
-- obstacles now (GROUND, below) -- a brick pyramid and a hump, far wider than
-- a pipe -- and their depths stay here only because the generator's notch
-- profile still describes them.
local SHAPES = {
  list = { "straight", "pentagon", "teeth" },
  depth = { straight = 0, triangle = 1.0, halfmoon = 0.8, pentagon = 0.65, teeth = 0.85 },
  teeth = 3, -- mirrors TEETH in the generator
  -- chance is filled in with the rest of the gameSetting.csv values below,
  -- which are not readable this early in the file
}

-- Depth in px that `shape`'s tip reaches past the flat edge, at -1 <= u <= 1
-- across the painted body. Mirrors notch_at() in the generator script; the
-- two have to agree or the art stops matching what kills you.
local function shapeNotchPx(shape, u)
  local depth = (SHAPES.depth[shape] or 0) * JAW.notch
  if depth <= 0 then return 0 end
  local a = math.abs(u)
  if a >= 1 then return 0 end
  if shape == "triangle" then
    return depth * (1 - a)
  elseif shape == "halfmoon" then
    return depth * math.sqrt(math.max(0, 1 - a * a))
  elseif shape == "pentagon" then
    local flat = 0.45
    if a <= flat then return depth end
    return depth * (1 - (a - flat) / (1 - flat))
  elseif shape == "teeth" then
    -- A sawtooth across -1..1, taken on u rather than a so an odd number of
    -- teeth puts the middle one's point at u = 0, where pipeAim reads the
    -- tightest spot from.
    local t = (u + 1) * SHAPES.teeth / 2
    local f = t - math.floor(t)
    return depth * (1 - math.abs(2 * f - 1))
  end
  return 0
end

-- ---------- Ground obstacles ----------
-- A column's bottom half can be something standing on the ground instead of
-- a pipe: a stepped brick pyramid or a rounded hump. They are much wider than
-- a pipe and are not pipes at all, so they get their own art and their own
-- hitbox rather than a notch cut into a jaw. The art is generated by
-- tools/make_ground_obstacles.py; every number in `pyramid` and `humps`
-- mirrors a constant there and has to agree with it, exactly as JAW does
-- with the pipe generator.
--
-- Sizes are in lane pixels on both axes -- unlike pipes they are not
-- stretched by LANE_SCALE, since bricks drawn at one size and shown at
-- another would stop being square to the grid.
local GROUND = {
  kinds = { "pyramid", "hump" },
  -- Where both stand: a few pixels down into the top of the ground art, so
  -- they read as planted on it rather than hovering on its edge.
  baseY = LAND_TOP + 5,
  -- A pyramid is `rows` courses of bricks, one brick narrower (half a brick
  -- in from each side) per course, with a single brick on top.
  pyramid = { brickW = 28, brickH = 18, rows = { 3, 4, 5, 6 } },
  -- A hump is half an ellipse, w wide and h tall.
  humps = { { w = 150, h = 56 }, { w = 190, h = 74 }, { w = 230, h = 92 } },
  -- How much of the column's usual opening is left between the pipe hanging
  -- above and the obstacle's highest point, as a fraction of it. Set by
  -- simulation so each is about as hard to get past as the narrow pipe tip
  -- it replaced (see the README entry for 2026-09-28).
  open = { pyramid = 0.85, hump = 0.83 },
  -- chance is read from gameSetting.csv further down, with the others
}

-- Height, width and art for one obstacle of `kind` at size index `size`.
GROUND.dims = function(kind, size)
  if kind == "pyramid" then
    local rows = GROUND.pyramid.rows[size]
    return rows * GROUND.pyramid.brickH, rows * GROUND.pyramid.brickW
  end
  local h = GROUND.humps[size]
  return h.h, h.w
end

GROUND.image = function(kind, size, themeKey)
  return "Assets/" .. kind .. "_" .. themeKey .. "_" .. size .. ".png"
end

-- y of the obstacle's surface `dx` pixels either side of its centre, or nil
-- where there is no obstacle at all. This is what kills you, and it is the
-- same outline the art is drawn to.
GROUND.surfaceAt = function(kind, size, dx)
  local a = math.abs(dx)
  if kind == "pyramid" then
    local py = GROUND.pyramid
    local rows = py.rows[size]
    -- course k (0 at the bottom) spans (rows - k) bricks, so the courses
    -- still under this point are those with (rows - k) * brickW / 2 > a
    local courses = math.min(rows, math.ceil(rows - 2 * a / py.brickW))
    if courses <= 0 then return nil end
    return GROUND.baseY - courses * py.brickH
  end
  local h = GROUND.humps[size]
  local r = a / (h.w / 2)
  if r >= 1 then return nil end
  return GROUND.baseY - h.h * math.sqrt(1 - r * r)
end
local BIRD_LOCAL_X = 90 * LANE_SCALE
local PIPE_SPAWN_X = LANE_W + 40
local TICK_DT = 0.025
local TOTAL_ROUNDS = 5
local AI_DELAY_TICKS = 4 -- 4 * 25ms tick = 100ms reaction lag on the AI's controller

-- Deliberate handicap so the AI doesn't just win every round outright: every
-- 5 pipes it clears, it rolls a fresh 15%-30% chance to lose right there.
-- A "loss" is just forcing the same death lane.alive=false/rotation=90 state
-- a real collision produces (see updateLane), so it reads the same as any
-- other crash instead of looking like a scripted event. Declared up here
-- (not next to the AI's other tuning constants further down) because
-- updateLane -- which is defined earlier in the file than updateAI -- is
-- what actually applies the roll, and needs these in scope by then.
local AI_LOSS_CHECK_PIPES = 5
local AI_LOSS_CHANCE_MIN = 0.15
local AI_LOSS_CHANCE_MAX = 0.30

-- Right-click dash (player only): a permanent forward skip. The bird's own
-- position never changes -- instead, all of the player's pipes and the
-- scrolling ground advance by an extra DASH_DISTANCE, i.e. the world
-- advances under the bird rather than the bird lunging out and being
-- pulled back to where it started. That extra distance is covered over
-- DASH_TRANSITION_TIME by boosting scroll speed for a few ticks, rather
-- than teleporting all of it in a single instant jump -- once it's covered,
-- scrolling just returns to normal and none of the gained ground is lost.
local DASH_DISTANCE = 150 * LANE_SCALE
local DASH_TRANSITION_TIME = 0.9 -- seconds for the extra distance to play out
local DASH_COOLDOWN = 2.5 -- seconds before another dash is allowed

-- How long the flap input (left click or the flap key) must be held, when
-- "hold to dash" is on, before it fires a dash instead of a flap. The
-- actual value (holdDashDelayMs, below) is adjustable in the keybind menu
-- via a slider between these bounds and persists across sessions.
local HOLD_DASH_DELAY_MIN_MS = 50
local HOLD_DASH_DELAY_MAX_MS = 600
local HOLD_DASH_DELAY_DEFAULT_MS = 200

-- ---------- Game settings (externalized to gameSetting.csv so the pipe
-- gap formula, the pipe-to-pipe spacing and the coin rate can all be tuned
-- without touching code) ----------
-- Sits up here, above every constant that reads it, because the coin spawn
-- rate just below is now the first of them.
-- File format is "setting,value" rows (a header row is skipped since it
-- doesn't parse as a number). A missing file or a missing individual key
-- falls back to the hardcoded default at its own call site, so a malformed
-- CSV can't break the build.
local function loadGameSettings()
  local settings = {}
  local path = system.pathForFile("gameSetting.csv", system.ResourceDirectory)
  local file = path and io.open(path, "r")
  if file then
    for line in file:lines() do
      local key, value = line:match("^%s*([%a_][%w_]*)%s*,%s*(-?[%d%.]+)%s*$")
      if key then
        settings[key] = tonumber(value)
      end
    end
    io.close(file)
  end
  return settings
end

local gameSettings = loadGameSettings()
local function settingOrDefault(key, default)
  local v = gameSettings[key]
  if v == nil then return default end
  return v
end

-- ---------- Coins ----------
-- A pickup that scrolls in from the right exactly like a pipe. Touching one
-- neither gains nor costs the collector any points -- it's an attack
-- instead: COIN_PIPE_DELAY seconds later, one pipe is generated in the
-- OTHER lane (the player collecting a coin puts a pipe on the AI's screen,
-- and vice versa). Since pipes never spawn on their own any more (see
-- "On-demand pipes" below), coins are the only thing that puts an obstacle
-- on either screen. A coin that scrolls past untouched just fizzles.
local DOT_SIZE = 22 * LANE_SCALE
local DOT_HIT_RADIUS = 22 * LANE_SCALE -- generous relative to DOT_SIZE/2 since it's a small target flown past at speed
-- The wait before each coin is rolled uniformly between these two, both
-- tunable in gameSetting.csv. The defaults are the original 3.5-7.0s window
-- divided by 5: with pipes now coming only from coins, the original rate
-- left both lanes near-empty, and even 3x was sparse enough that a round
-- could end 0-0 with barely a pipe to clear.
local DOT_SPAWN_MIN_INTERVAL = settingOrDefault("coin_spawn_interval_min", 0.7)
-- Clamped up to the min rather than trusted as-is: a max below it would
-- make rollNextDotSpawnIn return negative waits and spawn a coin every
-- single tick, which is a silent flood rather than the loud startup error a
-- bad gap_roll_min/max pair produces.
local DOT_SPAWN_MAX_INTERVAL = math.max(DOT_SPAWN_MIN_INTERVAL,
  settingOrDefault("coin_spawn_interval_max", 1.4))
-- How long after a coin is collected the opposing lane's pipe shows up.
-- This doubles as the flight time of the animation below, so the coin lands
-- exactly as the pipe it earned scrolls in.
local COIN_PIPE_DELAY = 1.0 -- seconds

-- The collected coin doesn't just vanish: it's knocked out of its lane and
-- bounces across to the right edge of the OTHER lane -- the point that
-- lane's pipes scroll in from -- so a player can see an obstacle coming and
-- who sent it, the way a Tetris garbage line telegraphs itself before it
-- lands. Both directions animate: your pickup flies right into the AI's
-- lane, the AI's flies left into yours.
local COIN_FLIGHT_HOPS = 3 -- arcs traced on the way across
local COIN_FLIGHT_HOP_HEIGHT = 80 * LANE_SCALE
local COIN_FLIGHT_SPINS = 2 -- full rotations over the trip

-- Original formula was the literal expression "100 + 20 * math.random(1, 10)"
-- (gaps land on 120, 140, ... 300); each piece is now its own tunable value.
-- ---------- Opening size, shapes and clamps (gameSetting.csv) ----------
-- Half the height of a pipe's opening, before any shape bites into it. Was a
-- hardcoded 50 and is now the reference every other number here is measured
-- against, including the AI's bob.
local GAP_HALF_H = settingOrDefault("pipe_gap_half_height", 50)

-- Chance a pipe gets a shaped tip (triangle/half-moon/pentagon) rather than
-- the flat one pipes have always had. 0 restores the old game exactly.
SHAPES.chance = settingOrDefault("pipe_shaped_chance", 0.35)

-- Chance a column's bottom half is a ground obstacle (pyramid or hump) rather
-- than a pipe. Rolled for any column with something on the bottom that did
-- not become a clamp or a breather, including the one-piece columns of the
-- opening era. The 0.25 default is about the share of columns the triangle
-- and half-moon tips took between them when they were pipe shapes (0.55 of
-- columns shaped, two shapes out of four), and pipe_shaped_chance came down
-- to match, so the two remaining tips turn up about as often as before.
GROUND.chance = settingOrDefault("ground_obstacle_chance", 0.25)

-- Chance a pipe is a clamp instead: flat jaws that squeeze shut as it comes
-- at you. Rolled before the shape roll, and a clamp always keeps flat jaws --
-- a shaped tip on a closing opening stacks two narrowings and can leave
-- nothing to fly through.
local CLAMP = {}
CLAMP.chance = settingOrDefault("clamp_pipe_chance", 0.18)

-- Seconds a clamp takes to close the whole way, counted only while it is on
-- screen so a pipe queued far off to the right does not arrive already shut.
-- The budget it has to fit inside: a pipe is visible for about 3.6s, and
-- reaches the bird about 2.1s in. 2.5s therefore closes slowly and visibly
-- the whole way across, and is about 85% shut at the moment you have to fly
-- through it. Set it past 3.6 and the pipe leaves the lane still closing, so
-- clamp_gap_min stops being reachable at all. Floored well clear of zero: at
-- 0 the division below would blow up.
CLAMP.closeTime = math.max(0.25, settingOrDefault("clamp_close_time", 2.5))

-- What a fully closed clamp leaves open, as a fraction of GAP_HALF_H. Held
-- inside 0.2..1 so a bad value cannot produce a pipe with no opening at all
-- (or one that closes into a wider gap than it started with).
CLAMP.gapMin = math.max(0.2, math.min(1, settingOrDefault("clamp_gap_min", 0.45)))

-- A breather is a clamp that does not stay shut: its flat jaws close and
-- reopen on a steady rhythm the whole way across, so the question is when to
-- go through rather than whether there is room. Rolled only for a two-jaw
-- column that did not become a clamp, and keeps flat jaws for the same reason
-- a clamp does. It is always wide open on the frame it comes on screen, so
-- the first thing you see of one is the gap at its widest.
local BREATHE = {}
BREATHE.chance = settingOrDefault("breathe_pipe_chance", 0.12)
-- Seconds for one full close-and-reopen. Floored so the jaws cannot strobe.
BREATHE.period = math.max(0.5, settingOrDefault("breathe_period", 1.6))
-- How far it closes at the tightest point of each breath, as a fraction of
-- GAP_HALF_H. Looser than CLAMP.gapMin by default: a breather's squeeze
-- comes round again every period, so it is met far more often than a
-- clamp's single close.
BREATHE.gapMin = math.max(0.2, math.min(1, settingOrDefault("breathe_gap_min", 0.55)))

-- A drifting column slides slowly up and down as it comes, jaws and opening
-- together, so the height you lined up for is not quite the height you
-- arrive at. It can be any column -- one jaw or two, flat or shaped -- except
-- a clamp or a breather, since a moving opening that is also changing size
-- asks two things of you at once. The drift starts at a random point in its
-- swing and, like a clamp, only advances while the pipe is on screen.
local DRIFT = {}
DRIFT.chance = settingOrDefault("drift_pipe_chance", 0.2)
-- Pixels either side of where the column was placed. Held under
-- GAP_HALF_H: the most a column is ever placed away from the edge of where
-- gaps can go is less than that, so this keeps a drifting opening from
-- sliding into the ceiling or the floor.
DRIFT.amp = math.max(0, math.min(GAP_HALF_H, settingOrDefault("drift_amplitude", 35)))
-- Seconds for one full swing down and back. Floored for the same reason as
-- a breather's period.
DRIFT.period = math.max(0.5, settingOrDefault("drift_period", 3.0))

-- ---------- Difficulty ramp over a round (gameSetting.csv) ----------
-- A round opens gently and works up. Three eras, on a clock that restarts
-- from zero every round:
--   0..ramp_single_pipe_until  every column carries ONE jaw, hanging from
--                              the ceiling or standing off the floor, with
--                              open lane above or below it to fly round
--   ..ramp_two_pipe_by         columns gradually start arriving with both
--                              jaws -- a real gap -- mixed in with singles
--   ramp_tighten_at..by        that gap closes from wide down to tight
-- Note the whole curve is per round, so the later eras only turn up in a run
-- that actually lasts that long: at ramp_tighten_at = 120 you have to stay
-- alive two minutes on one life to see the gaps tighten.
local RAMP = {
  singleUntil = settingOrDefault("ramp_single_pipe_until", 30),
  twoBy = settingOrDefault("ramp_two_pipe_by", 90),
  tightenAt = settingOrDefault("ramp_tighten_at", 120),
  tightenBy = settingOrDefault("ramp_tighten_by", 180),
  gapWide = settingOrDefault("ramp_gap_wide", 1.35),
  gapTight = settingOrDefault("ramp_gap_tight", 0.85),
}
-- Keep each era ending after it starts, whatever the file asks for: a
-- backwards pair would make rampLerp divide by a negative span.
RAMP.twoBy = math.max(RAMP.singleUntil + 1, RAMP.twoBy)
RAMP.tightenBy = math.max(RAMP.tightenAt + 1, RAMP.tightenBy)

-- Seconds into the current round. Reset by onFlapInput when a round starts
-- and advanced by gameLoop; both lanes read the same number, so the two
-- sides always face the same era of the ramp.
local roundElapsed = 0

-- Least open lane a one-jaw column ever leaves, measured from its edge to
-- the ceiling or the floor. Expressed against GAP_HALF_H so it keeps its
-- proportions if the opening is retuned; four times the half-gap is a very
-- forgiving hole, which is the point of the first era.
RAMP.singleOpenMin = GAP_HALF_H * 4

local function rampLerp(t, fromT, toT, fromV, toV)
  if t <= fromT then return fromV end
  if t >= toT then return toV end
  return fromV + (toV - fromV) * ((t - fromT) / (toT - fromT))
end

-- Chance the next column arrives with both jaws rather than just one.
local function twoJawChance()
  return rampLerp(roundElapsed, RAMP.singleUntil, RAMP.twoBy, 0, 1)
end

-- What to multiply the base opening by right now: wide while two-jaw columns
-- are still arriving, closing down to tight once past ramp_tighten_at.
local function rampGapScale()
  return rampLerp(roundElapsed, RAMP.tightenAt, RAMP.tightenBy, RAMP.gapWide, RAMP.gapTight)
end

-- The newer pipe kinds are held back and phased in on the same round clock,
-- so a round works up through them instead of meeting them all from the
-- first column. Each has a window: absent before `from`, then its chance
-- climbs from nothing to the full drift_/breathe_ chance (or, for teeth, to
-- an equal share of the shape roll) by `to`. The defaults slot them into
-- the eras above -- drift across the one-jaw opening, teeth as columns start
-- pairing up, breathers once most columns have both jaws to breathe with.
RAMP.unlocks = {
  drift = { from = settingOrDefault("ramp_drift_from", 10), to = settingOrDefault("ramp_drift_by", 30) },
  teeth = { from = settingOrDefault("ramp_teeth_from", 20), to = settingOrDefault("ramp_teeth_by", 45) },
  breathe = { from = settingOrDefault("ramp_breathe_from", 45), to = settingOrDefault("ramp_breathe_by", 90) },
}
for _, w in pairs(RAMP.unlocks) do
  w.to = math.max(w.from, w.to) -- a backwards window just unlocks all at once at `from`
end

-- 0..1: how far `kind` has been phased in at this point in the round. Kept
-- in RAMP rather than as its own local; see the note on JAW about the
-- 200-local ceiling.
RAMP.unlocked = function(kind)
  local w = RAMP.unlocks[kind]
  if not w then return 1 end
  if w.to <= w.from then return roundElapsed >= w.from and 1 or 0 end
  return rampLerp(roundElapsed, w.from, w.to, 0, 1)
end

local GAP_BASE = settingOrDefault("gap_base", 100)
local GAP_INCREMENT = settingOrDefault("gap_increment", 20)
local GAP_ROLL_MIN = settingOrDefault("gap_roll_min", 1)
local GAP_ROLL_MAX = settingOrDefault("gap_roll_max", 10)

local function randomGapY()
  return GAP_BASE + GAP_INCREMENT * math.random(GAP_ROLL_MIN, GAP_ROLL_MAX)
end

-- ---------- Flip (not mirror) ----------
-- The AI lane's artwork is horizontally flipped (background, land, pipes,
-- and bird each get xScale = -1, applied per-image in buildLaneVisuals),
-- but layout and motion are NOT mirrored: the bird sits at the same
-- BIRD_LOCAL_X within its own lane, and pipes travel the same direction
-- (right to left) at the same lane-local positions on both sides. This
-- function is a passthrough kept only so every position write goes through
-- one place; positions are identical for both lanes, only the pixels of
-- each individual image are flipped.
local function laneDisplayX(lane, simX)
  return simX
end

-- ---------- On-demand pipes ----------
-- Nothing spawns pipes on a timer or rides a pre-built course: a lane stays
-- completely empty until the OPPOSING lane's bird collects a coin, which
-- generates exactly one pipe here COIN_PIPE_DELAY seconds later (queued in
-- updateLane, spawned by gameLoop). The two lanes therefore no longer fly
-- an identical shared course -- each one's obstacles are whatever the other
-- player earned for it -- so pipes are per-lane display objects created and
-- destroyed on demand rather than three recycled slots reading a shared
-- course table.
--
-- The spacing rules are unchanged from when pipes did ride a fixed course:
-- consecutive pipes in a lane are never closer than PIPE_SPACING (the
-- minimum), but every pipe_spacing_interval_min..max pipes one gap gets
-- stretched by a random pipe_spacing_expand_min..max fraction so the rhythm
-- isn't perfectly uniform. Since spawns are now driven by each lane's own
-- coin traffic instead of one shared course, the "pipes to go until the
-- next stretched gap" counter is per-lane state (lane.pipesUntilWideGap)
-- rather than a single shared one.
local PIPE_SPACING_INTERVAL_MIN = settingOrDefault("pipe_spacing_interval_min", 2)
local PIPE_SPACING_INTERVAL_MAX = settingOrDefault("pipe_spacing_interval_max", 7)
local PIPE_SPACING_EXPAND_MIN = settingOrDefault("pipe_spacing_expand_min", 0.20)
local PIPE_SPACING_EXPAND_MAX = settingOrDefault("pipe_spacing_expand_max", 0.30)

local function rollPipesUntilWideGap()
  return math.random(PIPE_SPACING_INTERVAL_MIN, PIPE_SPACING_INTERVAL_MAX)
end

-- Minimum distance to leave between a lane's newest pipe and the one before
-- it. Every rollPipesUntilWideGap()-th call returns a stretched gap instead
-- of the plain minimum; the countdown lives on the lane, so each side's
-- rhythm follows its own pipe count.
local function nextPipeSpacing(lane)
  lane.pipesUntilWideGap = lane.pipesUntilWideGap - 1
  if lane.pipesUntilWideGap <= 0 then
    lane.pipesUntilWideGap = rollPipesUntilWideGap()
    local expandFrac = PIPE_SPACING_EXPAND_MIN + math.random() * (PIPE_SPACING_EXPAND_MAX - PIPE_SPACING_EXPAND_MIN)
    return PIPE_SPACING * (1 + expandFrac)
  end
  return PIPE_SPACING
end

-- ---------- Match state ----------
local match = {
  round = 1,
  playerTotal = 0,
  aiTotal = 0,
  bestTotal = 0,
  phase = "ready", -- ready | playing | roundover | matchover
  eliminated = nil, -- "you" | "ai" | "both" -- who went down to end the round
}

local function loadBestTotal()
  local path = system.pathForFile("bestscore.txt", system.DocumentsDirectory)
  local file, err = io.open(path, "r")
  if not file then
    print("File error: " .. tostring(err))
  else
    match.bestTotal = tonumber(file:read("*a")) or 0
    io.close(file)
  end
end

local function saveBestTotal()
  local path = system.pathForFile("bestscore.txt", system.DocumentsDirectory)
  local file, err = io.open(path, "w")
  if not file then
    print("File error: " .. tostring(err))
  else
    file:write(tostring(match.bestTotal))
    io.close(file)
  end
end

-- ---------- Keyboard bindings ----------
-- User-adjustable via the in-game keybind menu (see the settings button UI
-- further down), persisted to DocumentsDirectory the same way bestscore.txt
-- is -- unlike gameSetting.csv, which is a bundled/shipped design-tuning
-- file, this is per-player runtime preference.
local keyBindings = { flap = "space", dash1 = "z", dash2 = "right" }

-- Whether holding the flap input (left click or the flap key) for
-- holdDashDelayMs triggers a dash, toggled via the checkbox in the
-- keybind menu. Persisted alongside keyBindings even though neither is a
-- key binding itself, since they live in the same per-player preferences
-- file.
local holdToDashEnabled = false
local holdDashDelayMs = HOLD_DASH_DELAY_DEFAULT_MS

local function loadKeyBindings()
  local path = system.pathForFile("keybinds.txt", system.DocumentsDirectory)
  local file = path and io.open(path, "r")
  if file then
    for line in file:lines() do
      local key, value = line:match("^(%a+)=([%w]+)$")
      if key and keyBindings[key] ~= nil then
        keyBindings[key] = value
      elseif key == "holdToDash" then
        holdToDashEnabled = (value == "true")
      elseif key == "holdDashDelayMs" then
        local ms = tonumber(value)
        if ms then
          holdDashDelayMs = math.max(HOLD_DASH_DELAY_MIN_MS, math.min(HOLD_DASH_DELAY_MAX_MS, ms))
        end
      end
    end
    io.close(file)
  end
end

local function saveKeyBindings()
  local path = system.pathForFile("keybinds.txt", system.DocumentsDirectory)
  local file, err = io.open(path, "w")
  if not file then
    print("File error: " .. tostring(err))
  else
    file:write("flap=" .. keyBindings.flap .. "\n")
    file:write("dash1=" .. keyBindings.dash1 .. "\n")
    file:write("dash2=" .. keyBindings.dash2 .. "\n")
    file:write("holdToDash=" .. tostring(holdToDashEnabled) .. "\n")
    file:write("holdDashDelayMs=" .. tostring(math.floor(holdDashDelayMs + 0.5)) .. "\n")
    io.close(file)
  end
end

-- ---------- Lanes ----------
local function newLane(isAI)
  -- "frame" is a container purely so pipes/etc. that are momentarily
  -- positioned outside 0..LANE_W (e.g. a freshly spawned pipe waiting to
  -- scroll in) are clipped instead of bleeding into the other lane. It is
  -- never scaled -- the AI lane's flip is applied per-image instead, in
  -- buildLaneVisuals.
  local frame = display.newContainer(LANE_W, LANE_H)
  local content = display.newGroup()
  frame:insert(content)
  content.x = -LANE_W / 2
  content.y = -LANE_H / 2

  return {
    isAI = isAI,
    frame = frame,
    group = content,
    pipes = {},
    pipeGroup = nil,
    pipesUntilWideGap = rollPipesUntilWideGap(),
    dots = {},
    dotGroup = nil,
    bird = nil,
    background = nil,
    land = nil,
    landSimX = LANE_W,
    scoreText = nil,
    label = nil,
    alive = false,
    score = 0,
    velocityY = 0,
    aiCooldown = 0,
    aiDelayQueue = {},
    aiBobPhase = 0,
    dashCooldownRemaining = 0,
    dashRemaining = 0,
  }
end

local function buildLaneVisuals(lane)
  local g = lane.group
  local flip = lane.isAI and -1 or 1

  lane.background = display.newImageRect(g, getCurrentTheme().background, LANE_W, LANE_H)
  lane.background.x = laneDisplayX(lane, LANE_W / 2)
  lane.background.y = LANE_H / 2
  lane.background.xScale = flip

  local landH = LANE_H * LAND_HEIGHT_FRACTION
  lane.land = display.newImageRect(g, getCurrentTheme().land, LANE_W * 2, landH)
  lane.land.x = laneDisplayX(lane, lane.landSimX)
  lane.land.y = LANE_H - landH / 2
  lane.land.xScale = flip

  -- The lane starts with no pipes at all -- they're created on demand by
  -- spawnPipe as the other lane earns them. They go into their own group,
  -- created here between the land and the bird purely for z-order: dropping
  -- each new pipe straight into `g` would stack it above the bird and the
  -- score text (both built below) instead of behind them.
  lane.pipeGroup = display.newGroup()
  g:insert(lane.pipeGroup)

  -- Coins need the same treatment for the same reason: spawned straight into
  -- `g` they landed on top of the bird, the score and the lane label (a coin
  -- can sit as high as CEIL_LIMIT, which is level with the score readout).
  -- Their own group, inserted after the pipes', keeps them above the pipes
  -- and behind everything built below.
  lane.dotGroup = display.newGroup()
  g:insert(lane.dotGroup)

  -- the AI flies a whitened recolor of the same sprite sheet (a plain
  -- grayscale tint reads as pale gray, not white, since the fur's mid-tones
  -- never reach anywhere near 255 -- see make_bird_white.py) and, unlike
  -- the rest of its lane's art, is NOT flipped: it faces right, same as
  -- the player, rather than mirroring the flipped background/pipes
  local birdImage = lane.isAI and "Assets/bird_white.png" or "Assets/bird.png"
  local sheet = graphics.newImageSheet(birdImage, {
    width = 280, height = 200, numFrames = 4,
    sheetContentWidth = 1120, sheetContentHeight = 200,
  })
  local seq = { name = "walking", start = 1, count = 3, time = 300, loopCount = 2, loopDirection = "forward" }
  lane.bird = display.newSprite(g, sheet, seq)
  lane.bird.xScale = 0.25 * LANE_SCALE
  lane.bird.yScale = 0.25 * LANE_SCALE
  lane.bird.x = laneDisplayX(lane, BIRD_LOCAL_X)
  lane.bird.y = LANE_H * 0.42

  -- text is never flipped -- it's positioned identically in both lanes
  -- (LANE_W/2, i.e. each lane's own center) and always renders normally
  lane.scoreText = display.newText({ text = "0", x = 0, y = 0, font = "Assets/troika.otf", fontSize = 36 })
  g:insert(lane.scoreText)
  lane.scoreText.x = laneDisplayX(lane, LANE_W / 2)
  lane.scoreText.y = 50
  lane.scoreText:setFillColor(1, 1, 1)

  lane.label = display.newText({ text = lane.isAI and "AI" or "YOU", x = 0, y = 0, font = "Assets/troika.otf", fontSize = 20 })
  g:insert(lane.label)
  lane.label.x = laneDisplayX(lane, LANE_W / 2)
  lane.label.y = 88
  lane.label:setFillColor(1, 1, 1)
end

local function applyThemeToLane(lane)
  lane.background.fill = { type = "image", filename = getCurrentTheme().background }
  lane.land.fill = { type = "image", filename = getCurrentTheme().land }
  -- re-skin whatever pipes this lane happens to be holding at the moment;
  -- the two lanes no longer carry the same pipes, so each re-rolls its own
  for _, p in ipairs(lane.pipes) do
    p.skin = randomPipeSkin()
    local jaw = jawImage(p.skin, p.shape) -- the shape survives a theme swap
    if p.topJaw then p.topJaw.fill = { type = "image", filename = jaw } end
    if p.botJaw then p.botJaw.fill = { type = "image", filename = jaw } end
    if p.groundImg then
      p.groundImg.fill = { type = "image", filename = GROUND.image(p.ground, p.groundSize, getCurrentTheme().key) }
    end
  end
end

local function resetLane(lane)
  lane.alive = true
  lane.score = 0
  lane.scoreText.text = "0"
  lane.velocityY = FLAP_VY * 0.6
  lane.bird.y = LANE_H * 0.42
  lane.bird.rotation = 0
  lane.bird.alpha = 1
  lane.aiCooldown = 0

  -- pre-fill so the FIFO immediately has AI_DELAY_TICKS entries; without
  -- this the queue would start empty and the first few ticks would have
  -- zero delay (insert-then-remove only holds a fixed backlog once it's
  -- already at that size)
  lane.aiDelayQueue = {}
  for _ = 1, AI_DELAY_TICKS do
    lane.aiDelayQueue[#lane.aiDelayQueue + 1] = 0
  end
  lane.aiBobPhase = math.random() * 6.28
  lane.aiLastTarget, lane.aiLastAimY = nil, 0 -- updateAI's drift feed-forward

  lane.dashCooldownRemaining = 0
  lane.dashRemaining = 0

  for _, d in ipairs(lane.dots) do
    d.display:removeSelf()
  end
  lane.dots = {}

  lane.landSimX = LANE_W

  -- every round opens on a completely clear lane: the first pipe only shows
  -- up once the other lane's bird has collected a coin
  for _, p in ipairs(lane.pipes) do
    p:removeSelf()
  end
  lane.pipes = {}
  lane.pipesUntilWideGap = rollPipesUntilWideGap()
end

-- Puts a pipe's two jaw images either side of its opening. Called once when
-- the pipe is built and again on every tick a clamp closes a little further.
-- A jaw image carries JAW.notch of shaped tip below the row that represents a
-- flat edge, so the image sits that much lower than its own half-height.
local function layoutPipeJaws(pipe)
  local edge = JAW.h / 2 - JAW.notch
  if pipe.topJaw then pipe.topJaw.y = -pipe.gapHalf - edge end
  if pipe.botJaw then pipe.botJaw.y = pipe.gapHalf + edge end
end

-- Where the AI should aim at this column, and how much room it has there.
-- For a two-jaw column that is the middle of the gap, tightest point first.
-- A one-jaw column has no middle -- the open lane runs from its single edge
-- out to the ceiling or the floor -- so it aims at the middle of that open
-- lane instead. Worked out fresh on every call rather than stored at spawn,
-- since a drifting column carries its edge up and down with it.
local function pipeAim(pipe)
  if pipe.hasTop and pipe.hasBot then
    return pipe.y, pipe.gapHalf - shapeNotchPx(pipe.shape, 0)
  end
  if pipe.hasTop then
    local edgeY = pipe.y - pipe.gapHalf
    return (edgeY + GROUND_LIMIT) / 2, (GROUND_LIMIT - edgeY) / 2
  end
  local edgeY = pipe.y + pipe.gapHalf
  return (CEIL_LIMIT + edgeY) / 2, (edgeY - CEIL_LIMIT) / 2
end

-- Half the opening at `atX`, in lane coordinates: the pipe's current opening
-- (which a clamp shrinks over time) minus however far its tip bites in at
-- that point across. This is the one place the shape turns into something
-- that can kill you, and it is the same profile the art was drawn from.
local function pipeGapHalfAt(pipe, atX)
  local u = (atX - pipe.simX) / (PIPE_HALF_W * JAW.artHalf)
  return pipe.gapHalf - shapeNotchPx(pipe.shape, u)
end

local function laneCollides(lane, pipe)
  if BIRD_LOCAL_X > pipe.simX - PIPE_HALF_W and BIRD_LOCAL_X < pipe.simX + PIPE_HALF_W then
    local half = pipeGapHalfAt(pipe, BIRD_LOCAL_X)
    -- Only the jaws this column actually has can hit you: a ceiling-only
    -- column leaves the whole lane below it open, and vice versa.
    if pipe.hasTop and lane.bird.y < pipe.y - half then return true end
    if pipe.hasBot and not pipe.ground and lane.bird.y > pipe.y + half then return true end
  end
  -- A ground obstacle is far wider than the pipe above it, so it is tested
  -- across its own width against its own outline.
  if pipe.ground then
    local surface = GROUND.surfaceAt(pipe.ground, pipe.groundSize, BIRD_LOCAL_X - pipe.simX)
    if surface and lane.bird.y > surface then return true end
  end
  return false
end

-- Clearance kept between a coin and a pipe, so neither rides in on top of
-- (or visually touching) the other -- half a pipe's width plus the coin's
-- own full size. Pipes and coins are placed by independent spawners now,
-- rather than coins being slotted into a course the pipes already defined,
-- so each has to be nudged clear of the other explicitly.
local COIN_PIPE_CLEARANCE = PIPE_HALF_W + DOT_SIZE

-- Slides `simX` right until it clears every entry of the lists passed after
-- it (any lists of things carrying a .simX) by COIN_PIPE_CLEARANCE. Walking
-- them in ascending order means one pass settles it: each push can only move
-- simX further right, i.e. toward entries not yet checked. Takes several
-- lists because a spot usually has to clear both kinds of object at once,
-- and clearing them one list at a time could undo the previous pass.
local function pushClearOf(simX, ...)
  local xs = {}
  for _, list in ipairs({ ... }) do
    for _, o in ipairs(list) do
      xs[#xs + 1] = o.simX
    end
  end
  table.sort(xs)
  for _, x in ipairs(xs) do
    if math.abs(x - simX) < COIN_PIPE_CLEARANCE then
      simX = x + COIN_PIPE_CLEARANCE
    end
  end
  return simX
end

-- True when nothing in `others` sits within COIN_PIPE_CLEARANCE of `simX`.
-- Used where a spot has to be accepted or rejected as-is rather than nudged:
-- pushing a between-the-pipes coin to the right would shove it through the
-- pipe the midpoint was measured from.
local function isClearOf(simX, others)
  for _, o in ipairs(others) do
    if math.abs(o.simX - simX) < COIN_PIPE_CLEARANCE then
      return false
    end
  end
  return true
end

-- Generates one pipe in `lane`, riding in from off-screen right exactly the
-- way course pipes used to. Called only by the delayed coin payoff in
-- gameLoop -- nothing spawns pipes on a timer. The spacing rules are kept
-- by placing it a full nextPipeSpacing() behind the lane's current
-- rightmost pipe whenever that already sits further out than the normal
-- spawn point, so a lane fed a burst of coins gets its pipes queued up at
-- proper spacing instead of stacked on top of each other.
local function spawnPipe(lane)
  -- A pipe is a group holding two jaws, not a single image: the opening
  -- between them is set at runtime rather than baked into the picture, which
  -- is what lets a clamp close. The group's own y doubles as the centre of
  -- the opening, exactly as the old image's y did, so everything that reads
  -- p.y (the AI's target, coin placement) is unchanged.
  local p = display.newGroup()
  lane.pipeGroup:insert(p)
  p.scored = false
  p.skin = randomPipeSkin()

  -- How far this column's opening reaches from p.y out to a jaw edge. The
  -- ramp widens it while two-jaw columns are still being introduced and
  -- closes it down again past ramp_tighten_at.
  p.gapHalf = GAP_HALF_H * rampGapScale()
  p.gapHalfBase = p.gapHalf
  p.clampT = 0

  p.hasTop = true
  p.hasBot = true
  if math.random() >= twoJawChance() then
    -- Early in the round a column carries one jaw only, and the whole lane
    -- past its edge is open to fly through.
    if math.random() < 0.5 then p.hasBot = false else p.hasTop = false end
  end

  -- Only a two-jaw column can clamp: there has to be something on both
  -- sides for the opening to squeeze shut between.
  p.clamping = p.hasTop and p.hasBot and math.random() < CLAMP.chance
  -- A breather needs both jaws for the same reason, and is only rolled for a
  -- column the clamp roll passed over, so the two never stack.
  p.breathing = p.hasTop and p.hasBot and not p.clamping
    and math.random() < BREATHE.chance * RAMP.unlocked("breathe")
  p.breathT = 0

  -- The bottom half may be a pyramid or a hump standing on the ground. The
  -- pipe above one keeps a flat tip: a shaped tip biting down on top of an
  -- obstacle reaching up would narrow the same opening from both sides.
  if p.hasBot and not p.clamping and not p.breathing and math.random() < GROUND.chance then
    p.ground = GROUND.kinds[math.random(#GROUND.kinds)]
    local sizes = p.ground == "pyramid" and #GROUND.pyramid.rows or #GROUND.humps
    p.groundSize = math.random(sizes)
    p.gapHalf = p.gapHalf * GROUND.open[p.ground]
    p.gapHalfBase = p.gapHalf
  end

  p.shape = "straight"
  if not p.clamping and not p.breathing and not p.ground and math.random() < SHAPES.chance then
    -- index 1 is "straight", so roll across the shaped ones only. A shape
    -- that is still being phased in (see RAMP.unlocks) is weighted by how
    -- far in it is: teeth at half-unlocked are half as likely as any other
    -- shape, and at nothing the roll falls to the rest.
    local total = 0
    for i = 2, #SHAPES.list do total = total + RAMP.unlocked(SHAPES.list[i]) end
    local r = math.random() * total
    for i = 2, #SHAPES.list do
      local w = RAMP.unlocked(SHAPES.list[i])
      if w > 0 then
        p.shape = SHAPES.list[i]
        if r < w then break end
        r = r - w
      end
    end
  end

  -- Any column whose opening keeps its size may drift, shaped or not, one
  -- jaw or two. Starts at a random point in its swing so a run of drifters
  -- is not a row of pipes moving in lockstep.
  p.drifting = DRIFT.amp > 0 and not p.clamping and not p.breathing and not p.ground
    and math.random() < DRIFT.chance * RAMP.unlocked("drift")
  p.driftPhase = math.random() * 2 * math.pi

  if p.ground then
    -- Nothing to choose: the obstacle stands on the ground, so its peak is
    -- fixed by its height, and the opening sits directly on top of it. p.y
    -- is still the centre of the opening, so pipeAim needs no special case
    -- -- for a one-piece column its "edge" is simply the peak.
    local h = GROUND.dims(p.ground, p.groundSize)
    p.y = GROUND.baseY - h - p.gapHalf
  elseif p.hasTop and p.hasBot then
    p.y = randomGapY()
  else
    -- Place the single jaw by its EDGE rather than by a gap centre, so the
    -- lane it leaves open is a known size instead of whatever randomGapY
    -- happens to give once the ramp has scaled the opening. RAMP.singleOpenMin
    -- is the least it ever leaves.
    local lo, hi, edgeY
    if p.hasTop then
      lo, hi = CEIL_LIMIT + 60, GROUND_LIMIT - RAMP.singleOpenMin
      edgeY = math.random(math.floor(lo), math.floor(math.max(lo, hi)))
      p.y = edgeY + p.gapHalf
    else
      lo, hi = CEIL_LIMIT + RAMP.singleOpenMin, GROUND_LIMIT - 60
      edgeY = math.random(math.floor(math.min(lo, hi)), math.floor(hi))
      p.y = edgeY - p.gapHalf
    end
  end
  -- The drift swings about wherever the column was placed; p.y itself is
  -- what moves, so everything that reads it follows along.
  p.driftBaseY = p.y
  if p.drifting then
    p.y = p.driftBaseY + math.sin(p.driftPhase) * DRIFT.amp
  end

  local jaw = jawImage(p.skin, p.shape)
  if p.hasTop then
    p.topJaw = display.newImageRect(p, jaw, PIPE_HALF_W * 2, JAW.h)
  end
  if p.hasBot and not p.ground then
    p.botJaw = display.newImageRect(p, jaw, PIPE_HALF_W * 2, JAW.h)
    p.botJaw.yScale = -1 -- the bottom jaw is the same art stood on its head
  end
  layoutPipeJaws(p)

  -- How far the column reaches either side of its centre -- a pipe's
  -- half-width, or an obstacle's if it is wider. Spawning, spacing and
  -- clean-up all measure off this rather than off PIPE_HALF_W, or a wide
  -- obstacle would pop into view already half on screen and vanish while
  -- half of it was still showing.
  p.halfW = PIPE_HALF_W
  if p.ground then
    local h, w = GROUND.dims(p.ground, p.groundSize)
    p.groundImg = display.newImageRect(p, GROUND.image(p.ground, p.groundSize, getCurrentTheme().key), w, h)
    -- the group sits at p.y, the obstacle's feet at GROUND.baseY
    p.groundImg.y = GROUND.baseY - h / 2 - p.y
    p.halfW = math.max(PIPE_HALF_W, w / 2)
  end

  -- Placed last, now that its width is known. The spacing rule is between
  -- the EDGES of neighbouring columns rather than their centres, so two wide
  -- obstacles in a row keep the same clear run between them as two pipes.
  local simX = math.max(PIPE_SPAWN_X, LANE_W + p.halfW)
  local rightmost = nil
  for _, q in ipairs(lane.pipes) do
    if (not rightmost) or q.simX > rightmost.simX then rightmost = q end
  end
  -- rolled on every spawn, as it always was: it also advances the counter
  -- behind the occasional widened gap
  local spacing = nextPipeSpacing(lane)
  if rightmost then
    spacing = spacing + (rightmost.halfW - PIPE_HALF_W) + (p.halfW - PIPE_HALF_W)
    simX = math.max(simX, rightmost.simX + spacing)
  end
  simX = pushClearOf(simX, lane.dots)
  p.simX = simX

  p.xScale = lane.isAI and -1 or 1
  p.x = laneDisplayX(lane, simX)
  lane.pipes[#lane.pipes + 1] = p
end

-- Spawns one coin into `lane`. The preferred spot is the midpoint of an
-- open gap between two of the lane's pipes that's still ahead of the bird:
-- since PIPE_SPACING is much wider than a pipe's own PIPE_HALF_W, a
-- midpoint is clear of both regardless of y, instead of landing on top of
-- one or too close to be grabbable. Requiring the gap to be ahead of the
-- bird keeps a coin from appearing behind it, already uncatchable. A lane
-- now routinely holds fewer than two pipes (they only exist while the other
-- lane is collecting coins), so with no such gap available the coin simply
-- rides in from the usual off-screen spawn point instead, pushed clear of
-- anything already out there.
local function spawnDot(lane)
  local pipesByX = {}
  for _, p in ipairs(lane.pipes) do
    pipesByX[#pipesByX + 1] = p
  end
  table.sort(pipesByX, function(a, b) return a.simX < b.simX end)

  local candidates = {}
  for i = 1, #pipesByX - 1 do
    local a, b = pipesByX[i], pipesByX[i + 1]
    local midX = (a.simX + b.simX) / 2
    -- ...and clear of any coin already sitting there. Without this a coin
    -- riding in from off-screen and a later coin placed at a midpoint could
    -- land on exactly the same spot -- two coins drawn as one, both
    -- collected by a single pass, sending two pipes for one visible pickup.
    if midX > BIRD_LOCAL_X + 40 and isClearOf(midX, lane.dots) then
      candidates[#candidates + 1] = { a = a, b = b, simX = midX }
    end
  end

  local simX, y
  if #candidates > 0 then
    local pick = candidates[math.random(#candidates)]
    simX = pick.simX
    local aimA = pipeAim(pick.a)
    local aimB = pipeAim(pick.b)
    y = (aimA + aimB) / 2 + math.random(-20, 20)
  else
    simX = pushClearOf(PIPE_SPAWN_X, lane.pipes, lane.dots)
    y = randomGapY() + math.random(-20, 20)
  end
  -- Clamped to the ground's surface (LAND_TOP), not GROUND_LIMIT -- that's
  -- the deeper death line the bird can sink into, and a coin spawned that
  -- low would visually land inside the dirt. The coin is drawn from its
  -- centre, so the limit is half a coin above the surface: clamping the
  -- centre to LAND_TOP itself still buried the bottom half of it.
  y = math.max(CEIL_LIMIT, math.min(LAND_TOP - DOT_SIZE / 2, y))

  local img = display.newImageRect(lane.dotGroup, "Assets/gold.png", DOT_SIZE, DOT_SIZE)
  img.xScale = lane.isAI and -1 or 1
  img.x = laneDisplayX(lane, simX)
  img.y = y

  lane.dots[#lane.dots + 1] = { simX = simX, y = y, display = img }
end

-- Coin payoffs queued by updateLane (below): one entry per collected coin,
-- holding the lane that collected it and the countdown left before the
-- OTHER lane gets its pipe. updateLane can't resolve "the other lane" or
-- spawn into it itself: it's defined before playerLane/aiLane exist as
-- locals, so referencing them directly here would silently resolve as
-- globals instead (the same pitfall AI_LOSS_CHECK_PIPES hit once, see the
-- README). gameLoop ticks these down every frame -- deliberately on the
-- game's own clock rather than via timer.performWithDelay, so a pending
-- pipe freezes along with everything else while the keybind menu is open,
-- and is dropped cleanly when a round resets.
local pendingPipeSpawns = {}

local function flapLane(lane)
  if not lane.alive then return end
  lane.velocityY = FLAP_VY
  lane.bird:play()
  if not lane.isAI then
    audio.play(wingSound)
  end
end

local function updateLane(lane, dt)
  if not lane.alive then return end

  -- gravity only applies to the player; the AI lane's velocity is fully
  -- owned by updateAI's proportional controller (see the note there for why)
  if not lane.isAI then
    lane.velocityY = lane.velocityY + GRAVITY * dt
  end
  lane.bird.y = lane.bird.y + lane.velocityY * dt
  lane.bird.rotation = math.max(-30, math.min(70, lane.velocityY * 0.06))
  if lane.bird.y < CEIL_LIMIT then
    lane.bird.y = CEIL_LIMIT
  end

  if lane.dashCooldownRemaining > 0 then
    lane.dashCooldownRemaining = math.max(0, lane.dashCooldownRemaining - dt)
  end

  -- spend down any pending dash distance at a fixed extra rate so it plays
  -- out over DASH_TRANSITION_TIME as a burst of speed rather than an
  -- instant jump; once dashRemaining hits 0 scrolling just returns to
  -- SCROLL_SPEED, keeping all the ground already gained
  local dashStep = 0
  if lane.dashRemaining > 0 then
    dashStep = math.min(lane.dashRemaining, (DASH_DISTANCE / DASH_TRANSITION_TIME) * dt)
    lane.dashRemaining = lane.dashRemaining - dashStep
  end
  local scrollThisTick = SCROLL_SPEED * dt + dashStep

  local died = false
  if lane.bird.y > GROUND_LIMIT then
    lane.bird.y = GROUND_LIMIT
    died = true
  end

  lane.landSimX = lane.landSimX - scrollThisTick
  if lane.landSimX <= 0 then
    lane.landSimX = lane.landSimX + LANE_W
  end
  lane.land.x = laneDisplayX(lane, lane.landSimX)

  -- walked back-to-front so a pipe can be dropped from the list mid-loop
  for i = #lane.pipes, 1, -1 do
    local p = lane.pipes[i]
    p.simX = p.simX - scrollThisTick

    -- A clamp squeezes shut on its way across. The countdown only runs once
    -- the pipe is actually on screen, so one queued up behind a burst of
    -- coins arrives at the same stage of closing as any other rather than
    -- having quietly shut while it waited off to the right.
    if p.clamping and p.simX <= LANE_W + PIPE_HALF_W and p.clampT < CLAMP.closeTime then
      p.clampT = math.min(CLAMP.closeTime, p.clampT + dt)
      local closed = p.clampT / CLAMP.closeTime
      p.gapHalf = p.gapHalfBase * (1 - closed * (1 - CLAMP.gapMin))
      layoutPipeJaws(p)
    end

    -- Breathers and drifters run on the same on-screen-only clock. A
    -- breather's cosine starts at 1, i.e. wide open, the moment it appears.
    local onScreen = p.simX <= LANE_W + PIPE_HALF_W
    if p.breathing and onScreen then
      p.breathT = p.breathT + dt
      local open = 0.5 + 0.5 * math.cos(p.breathT / BREATHE.period * 2 * math.pi)
      p.gapHalf = p.gapHalfBase * (BREATHE.gapMin + (1 - BREATHE.gapMin) * open)
      layoutPipeJaws(p)
    end
    if p.drifting and onScreen then
      p.driftPhase = p.driftPhase + dt / DRIFT.period * 2 * math.pi
      p.y = p.driftBaseY + math.sin(p.driftPhase) * DRIFT.amp
    end

    if not died and (not p.scored) and p.simX < BIRD_LOCAL_X then
      p.scored = true
      lane.score = lane.score + 1
      lane.scoreText.text = tostring(lane.score)
      if not lane.isAI then
        audio.play(pointSound)
      end

      if lane.isAI and lane.score % AI_LOSS_CHECK_PIPES == 0 then
        local lossChance = AI_LOSS_CHANCE_MIN + math.random() * (AI_LOSS_CHANCE_MAX - AI_LOSS_CHANCE_MIN)
        if math.random() < lossChance then
          died = true
        end
      end
    end

    if p.simX < -p.halfW - 14 then
      -- nothing recycles any more: once a pipe is off the left edge it's
      -- gone for good, until the other lane earns this one another
      p:removeSelf()
      table.remove(lane.pipes, i)
    else
      p.x = laneDisplayX(lane, p.simX)

      if not died and laneCollides(lane, p) then
        died = true
      end
    end
  end

  for i = #lane.dots, 1, -1 do
    local d = lane.dots[i]
    d.simX = d.simX - scrollThisTick
    d.display.x = laneDisplayX(lane, d.simX)

    local remove = false
    if d.simX < -60 then
      remove = true -- missed -- scrolled off unclaimed, so no pipe is earned
    elseif not died
      and math.abs(BIRD_LOCAL_X - d.simX) < DOT_HIT_RADIUS
      and math.abs(lane.bird.y - d.y) < DOT_HIT_RADIUS
    then
      -- collecting it neither adds to nor takes from this lane's score; it
      -- queues a pipe for the OTHER lane, COIN_PIPE_DELAY seconds out.
      -- fromSimX/fromY are where the flight animation starts from, captured
      -- here because the coin itself is removed on the next line. The launch
      -- sound is played by beginCoinFlight rather than here, so that it
      -- fires for the AI's pickups too -- being sent a pipe should be as
      -- audible as sending one.
      remove = true
      pendingPipeSpawns[#pendingPipeSpawns + 1] = {
        from = lane,
        remaining = COIN_PIPE_DELAY,
        fromSimX = d.simX,
        fromY = d.y,
      }
    end

    if remove then
      d.display:removeSelf()
      table.remove(lane.dots, i)
    end
  end

  if died then
    lane.alive = false
    lane.bird.rotation = 90
    if not lane.isAI then
      audio.play(hitSound)
    end
  end
end

-- A single flap is a fixed, fairly strong impulse (FLAP_VY) meant for a
-- human tapping irregularly -- worked out on paper (and confirmed with a
-- standalone simulation of this exact physics), one flap swings the bird
-- roughly 60px if uncorrected, which is bigger than the pipe gap's own
-- +/-50px tolerance. That means no amount of clever *timing* of full-power
-- discrete flaps can reliably thread the gap: reactive, predictive, and
-- hysteresis-gated versions were all tried and all failed almost every run
-- in simulation. Instead, the AI flies on a proportional "autopilot" that
-- continuously blends its velocity toward a desired speed proportional to
-- how far it is from the gap center (capped, and eased in over each tick
-- rather than snapping) -- gravity is skipped for this lane in updateLane
-- so this is the sole author of its vertical motion. In 60 simulated
-- matches this reliably ran past 280 pipes (test was capped there) with
-- zero deaths, comfortably past the 5-20 pipe target.
local AI_KP = 4        -- desired speed per pixel of vertical error
local AI_CAP = 300     -- max commanded vertical speed (px/s)
local AI_BLEND = 0.3   -- fraction of the way to desired speed covered per tick
local AI_ANIM_INTERVAL = 0.3 -- just cosmetic: how often to replay the wing flap

-- The autopilot above reacts instantly, which is what made it fly this
-- well in the first place -- but that reads as inhumanly perfect. AI_DELAY_TICKS
-- (declared up with the other constants, since resetLane needs it too) gives
-- it a fixed 100ms reaction lag instead of slowing it down or making it
-- less accurate: each tick's computed correction is queued and only
-- actually applied AI_DELAY_TICKS ticks later, like a human noticing and
-- reacting to the gap slightly after the fact rather than an AI reading
-- the game state instantly.

-- On top of the lag, the target itself rides a slow sine wave instead of
-- sitting still, so the AI visibly bobs up and down in flight rather than
-- gliding to a dead stop on the gap's exact center -- closer to how a
-- human's altitude wanders a bit even while roughly tracking the gap.
-- Amplitude was found by simulation: 28-38px all survived 300/300 trials
-- with zero deaths, while 45px started killing it almost every run, so
-- 32px keeps a comfortable margin below that cliff.
local AI_BOB_AMPLITUDE = 32
-- That 32 was measured against a 50px half-opening. Shaped tips and clamps
-- both leave less than that, so the amplitude is held to the same share of
-- whatever the pipe actually leaves open rather than to the raw number --
-- which also means it tracks pipe_gap_half_height if that is retuned.
local AI_BOB_GAP_RATIO = AI_BOB_AMPLITUDE / GAP_HALF_H
local AI_BOB_SPEED = 3.5 -- radians/sec, ~1.8s per full bob cycle

local function updateAI(lane, dt)
  if not lane.alive then return end

  -- may find nothing at all: the lane is empty whenever the player hasn't
  -- fed it a pipe lately, in which case the autopilot just holds the
  -- resting altitude below
  local target, bestDist = nil, math.huge
  for _, p in ipairs(lane.pipes) do
    local dist = p.simX - BIRD_LOCAL_X
    if dist > -p.halfW and dist < bestDist then
      bestDist = dist
      target = p
    end
  end

  lane.aiBobPhase = lane.aiBobPhase + AI_BOB_SPEED * dt
  -- Wandering 32px inside an opening only 30px from centre to edge is a
  -- guaranteed crash, so the wander is sized off the tightest point of the
  -- pipe being flown at -- a triangle's point, or a clamp at whatever it has
  -- closed to this tick -- and not off the old fixed number.
  local aimY, aimHalf = LANE_H * 0.42, GAP_HALF_H
  if target then aimY, aimHalf = pipeAim(target) end
  -- A breather comes round to its tightest every period, and sizing the
  -- wander off how open it is *this* tick leaves the bird out near the edge
  -- when the jaws come back in -- the harness lost the AI to breathers that
  -- way more than to anything else. So it wanders only as far as the
  -- tightest breath allows.
  if target and target.breathing then
    aimHalf = math.min(aimHalf, target.gapHalfBase * BREATHE.gapMin)
  end
  local amplitude = math.min(AI_BOB_AMPLITUDE, aimHalf * AI_BOB_GAP_RATIO)
  local bob = math.sin(lane.aiBobPhase) * amplitude
  local targetY = aimY + bob

  -- Feed forward how fast the aim point itself is moving. The controller
  -- only pushes in proportion to how far off it is, so against a drifting
  -- column it settles into trailing it -- about 18px behind at full drift
  -- speed, which on top of the bob was enough to put it into a jaw. Only
  -- counted while it is still the same pipe, or switching to the next one
  -- would read as one enormous tick of motion.
  local aimV = 0
  if target and target == lane.aiLastTarget then
    aimV = (aimY - lane.aiLastAimY) / dt
  end
  lane.aiLastTarget, lane.aiLastAimY = target, aimY

  local error = targetY - lane.bird.y
  local desiredV = math.max(-AI_CAP, math.min(AI_CAP, error * AI_KP + aimV))

  table.insert(lane.aiDelayQueue, desiredV)
  local delayedV = table.remove(lane.aiDelayQueue, 1)

  lane.velocityY = lane.velocityY + (delayedV - lane.velocityY) * AI_BLEND

  lane.aiCooldown = lane.aiCooldown - dt
  if lane.aiCooldown <= 0 then
    lane.bird:play()
    lane.aiCooldown = AI_ANIM_INTERVAL
  end
end

-- ---------- Build the two lanes ----------
loadSounds()
loadBestTotal()
loadKeyBindings()

local playerLane = newLane(false)
local aiLane = newLane(true)
buildLaneVisuals(playerLane)
buildLaneVisuals(aiLane)

-- position each lane's clipping frame (its local origin is its own center,
-- so x/y here are screen midpoints, not top-left corners). LANE_W already
-- has LANE_GAP subtracted out, so the two frames land exactly LANE_GAP
-- pixels apart with a clean seam in between for the divider below.
playerLane.frame.x = SCREEN_LEFT + LANE_W / 2
playerLane.frame.y = SCREEN_TOP + LANE_H / 2

aiLane.frame.x = SCREEN_LEFT + display.actualContentWidth - LANE_W / 2
aiLane.frame.y = SCREEN_TOP + LANE_H / 2

local laneDivider = display.newRect(SCREEN_LEFT + display.actualContentWidth / 2, SCREEN_TOP + LANE_H / 2, LANE_GAP, LANE_H)
laneDivider:setFillColor(0.04, 0.04, 0.04)

resetLane(playerLane)
resetLane(aiLane)

local function otherLane(lane)
  return lane.isAI and playerLane or aiLane
end

-- ---------- Coin flight (the cross-lane "sent garbage") ----------
-- Each lane's frame is a display.newContainer, which clips its contents, so
-- a coin travelling between lanes cannot live in either lane's group -- it
-- would be cut off at the lane edge. Flights ride in this top-level group
-- instead, created here so it sits directly above both lane frames and the
-- divider, and below every HUD element built further down.
local coinFlightGroup = display.newGroup()

-- Lane-local coordinates out to screen coordinates. A lane frame is centered
-- on screen and its content group is offset by half the lane, which works out
-- to the lane's left edge plus the local x.
local function laneScreenX(lane, localX)
  local laneLeft = lane.isAI
    and (SCREEN_LEFT + display.actualContentWidth - LANE_W)
    or SCREEN_LEFT
  return laneLeft + localX
end

local function laneScreenY(localY)
  return SCREEN_TOP + localY
end

-- Starts the visual for one queued payoff: a coin lifted out of the lane
-- that collected it, at the exact spot it was taken, aimed at the ground at
-- the far right edge of the opposing lane.
local function beginCoinFlight(pending)
  local target = otherLane(pending.from)
  local img = display.newImageRect(coinFlightGroup, "Assets/gold.png", DOT_SIZE, DOT_SIZE)
  pending.flight = {
    display = img,
    x0 = laneScreenX(pending.from, pending.fromSimX),
    y0 = laneScreenY(pending.fromY),
    x1 = laneScreenX(target, LANE_W),
    y1 = laneScreenY(LAND_TOP),
  }
  img.x, img.y = pending.flight.x0, pending.flight.y0
  playCoinSound()
end

-- Advances a flight to `t` -- 0 at the pickup, 1 as the pipe lands. x is a
-- straight run across; y falls toward the ground line while a decaying |sin|
-- lifts it into COIN_FLIGHT_HOPS successively smaller arcs, so it reads as a
-- coin skipping across the screen rather than gliding over it. Both ends are
-- exact: the arc term is zero at t=0 and t=1, leaving y0 and y1 untouched.
local function updateCoinFlight(flight, t)
  local arc = math.abs(math.sin(t * math.pi * COIN_FLIGHT_HOPS)) * COIN_FLIGHT_HOP_HEIGHT * (1 - t)
  flight.display.x = flight.x0 + (flight.x1 - flight.x0) * t
  flight.display.y = flight.y0 + (flight.y1 - flight.y0) * t - arc
  flight.display.rotation = t * 360 * COIN_FLIGHT_SPINS
end

local function endCoinFlight(pending)
  if pending.flight then
    pending.flight.display:removeSelf()
    pending.flight = nil
  end
end

-- Drops every queued payoff along with its coin, so a flight left over from
-- the previous round can't land into a lane that has since been rebuilt or
-- leave its coin stranded mid-screen.
local function clearPendingPipeSpawns()
  for _, pending in ipairs(pendingPipeSpawns) do
    endCoinFlight(pending)
  end
  pendingPipeSpawns = {}
end

-- Counts down to the next steal-dot spawn; re-rolled after each spawn and
-- at the start of every round (see onFlapInput below).
local function rollNextDotSpawnIn()
  return DOT_SPAWN_MIN_INTERVAL + math.random() * (DOT_SPAWN_MAX_INTERVAL - DOT_SPAWN_MIN_INTERVAL)
end
local nextDotSpawnIn = rollNextDotSpawnIn()

-- ---------- Input plumbing (forward-declared; the full body is assigned
-- further down once refreshOverlay exists, but the tap catcher needs to be
-- created now, BELOW the theme button in z-order, so the button keeps
-- getting first claim on taps that land inside it) ----------
local onFlapInput
local finishRound -- forward-declared for the same reason; onFlapInput calls it
local tryDash -- forward-declared too: onKeyEvent (Z / right arrow) calls it before its real body is defined further down
local setDashIndicatorReady -- forward-declared too: onFlapInput resets it to "ready" at the start of every round, before its real body is defined further down

local screenCenterX = SCREEN_LEFT + display.actualContentWidth / 2
local screenCenterY = SCREEN_TOP + LANE_H / 2

-- Guards against Corona's synthetic "tap" event also firing for a
-- right-click (behavior isn't verified here, so this is cheap insurance):
-- a right-click dash marks a brief window during which a "tap" is ignored
-- instead of also triggering a flap.
local ignoreTapUntil = 0

-- Set right after "hold to dash" fires a dash from a held left click, so
-- the "tap" event generated when the button is finally released doesn't
-- also flap. Cleared the moment that one tap is swallowed -- and again at
-- the start of every press, because that swallowing tap does not always
-- arrive. The HUD buttons (theme, KEYS) carry a "tap" listener but no
-- "touch" one, so a press on them still reaches the tapCatcher underneath
-- and arms its hold timer, while the release's tap is claimed by the button
-- and never reaches the handler that would clear this. Holding either of
-- them with hold-to-dash on therefore left the flag set and ate the next
-- genuine flap. Clearing on "began" is safe: the tap that pairs with a
-- press is always delivered before the next press starts.
local holdDashSuppressTap = false

-- True while the keybind settings menu is open; guards every gameplay
-- input listener (tap, key, mouse) further down so a tap/keypress meant for
-- the menu never also flaps or dashes underneath it.
local menuOpen = false

-- Set to "flap"/"dash1"/"dash2" while the menu is waiting for the next
-- keypress to assign to that binding; nil the rest of the time.
local listeningForBinding = nil

-- Forward-declared: the menu UI (built further down) assigns this to update
-- its on-screen key labels after a rebind; onKeyEvent needs to call it
-- before that UI exists yet.
local refreshKeybindLabels

local tapCatcher = display.newRect(screenCenterX, screenCenterY, display.actualContentWidth, LANE_H)
tapCatcher:setFillColor(0, 0, 0, 0)
tapCatcher.isHitTestable = true
tapCatcher:addEventListener("tap", function()
  if menuOpen then
    return true
  end
  if system.getTimer() < ignoreTapUntil then
    return true
  end
  if holdDashSuppressTap then
    holdDashSuppressTap = false
    return true
  end
  onFlapInput()
  return true
end)

-- Touch mirror of onMouseEvent's hold-to-dash timer further down. Corona
-- raises "mouse" events only for a real pointer, so on a phone that timer
-- was never armed and the hold-to-dash option silently did nothing. The flap
-- still comes from the "tap" listener above -- this only watches for a press
-- held long enough to become a dash, and reuses holdDashSuppressTap so the
-- release tap is swallowed exactly the way it is for a mouse.
local holdDashTouchTimer = nil

local function cancelHoldDashTouchTimer()
  if holdDashTouchTimer then
    timer.cancel(holdDashTouchTimer)
    holdDashTouchTimer = nil
  end
end

tapCatcher:addEventListener("touch", function(event)
  if event.phase == "began" then
    cancelHoldDashTouchTimer()
    holdDashSuppressTap = false -- a stale one would eat this press's own tap
    if holdToDashEnabled and not menuOpen then
      holdDashTouchTimer = timer.performWithDelay(holdDashDelayMs, function()
        holdDashTouchTimer = nil
        if tryDash() then
          holdDashSuppressTap = true
        end
      end)
    end
  elseif event.phase == "ended" or event.phase == "cancelled" then
    cancelHoldDashTouchTimer()
  end
  return false
end)

-- ---------- Top-level UI (unflipped, spans the full width) ----------
local bestLabel = display.newText({ text = "BEST " .. match.bestTotal, x = SCREEN_LEFT + 70, y = SCREEN_TOP + 24, font = "Assets/troika.otf", fontSize = 16 })
bestLabel:setFillColor(1, 1, 1)

local themeToggleButton = display.newImageRect("Assets/theme_button.png", 96, 54)
themeToggleButton.x = SCREEN_LEFT + display.actualContentWidth - 56
themeToggleButton.y = SCREEN_TOP + 34
themeToggleButton.alpha = 0.92

local themeToggleLabel = display.newText({ text = getCurrentTheme().label, x = themeToggleButton.x, y = themeToggleButton.y + 30, font = "Assets/troika.otf", fontSize = 14 })
themeToggleLabel:setFillColor(0.35, 0.25, 0.12)

local function toggleTheme()
  currentThemeIndex = currentThemeIndex + 1
  if currentThemeIndex > #THEMES then
    currentThemeIndex = 1
  end
  -- applyThemeToLane re-rolls each lane's own live pipes into the new
  -- theme's skins; the lanes hold different pipes now, so there's nothing
  -- shared to keep in sync between them
  applyThemeToLane(playerLane)
  applyThemeToLane(aiLane)
  themeToggleLabel.text = getCurrentTheme().label
end
themeToggleButton:addEventListener("tap", function()
  toggleTheme()
  return true
end)

local overlayBackdrop = display.newRect(screenCenterX, screenCenterY, 640, 240)
overlayBackdrop:setFillColor(0, 0, 0, 0.62)

local overlayTitle = display.newText({ text = "", x = screenCenterX, y = screenCenterY - 60, width = 600, font = "Assets/troika.otf", fontSize = 34, align = "center" })
overlayTitle:setFillColor(1, 1, 1)

local overlaySubtitle = display.newText({ text = "", x = screenCenterX, y = screenCenterY + 25, width = 600, font = "Assets/troika.otf", fontSize = 19, align = "center" })
overlaySubtitle:setFillColor(0.92, 0.92, 0.92)

local function setOverlayVisible(visible)
  overlayBackdrop.isVisible = visible
  overlayTitle.isVisible = visible
  overlaySubtitle.isVisible = visible
end

-- The "spectating" phase and its banner are gone: under the elimination rule
-- a round ends the instant either bird goes down, so there is never an AI run
-- left to watch after the player crashes.
local function refreshOverlay()
  if match.phase == "playing" then
    setOverlayVisible(false)
    return
  end

  setOverlayVisible(true)

  if match.phase == "ready" then
    overlayTitle.text = "ROUND " .. match.round .. " / " .. TOTAL_ROUNDS
    overlaySubtitle.text = "TAP, CLICK, OR PRESS SPACE TO START"
  elseif match.phase == "roundover" then
    -- the headline is who went down, since that -- not the score -- is what
    -- ended the round
    if match.eliminated == "both" then
      overlayTitle.text = "BOTH ELIMINATED"
    elseif match.eliminated == "you" then
      overlayTitle.text = "YOU WERE ELIMINATED"
    else
      overlayTitle.text = "AI ELIMINATED"
    end
    overlaySubtitle.text = "ROUND " .. match.round .. "   -   YOU " .. playerLane.score .. "  -  AI " .. aiLane.score .. "     (tap for round " .. (match.round + 1) .. ")"
  elseif match.phase == "matchover" then
    local verdict
    if match.playerTotal > match.aiTotal then
      verdict = "YOU WIN THE RACE!"
    elseif match.aiTotal > match.playerTotal then
      verdict = "AI WINS THE RACE!"
    else
      verdict = "IT'S A TIE!"
    end
    overlayTitle.text = verdict
    overlaySubtitle.text = "TOTAL  YOU " .. match.playerTotal .. "  -  AI " .. match.aiTotal .. "   (best " .. match.bestTotal .. ")  -  tap to play again"
  end
end
refreshOverlay()

-- ---------- Input (real implementation; onFlapInput was forward-declared
-- above so the tap catcher could be wired up before the theme button) ----------
onFlapInput = function()
  if match.phase == "playing" then
    flapLane(playerLane)
    return
  end

  if match.phase == "matchover" then
    match.round = 1
    match.playerTotal = 0
    match.aiTotal = 0
  elseif match.phase == "roundover" then
    match.round = match.round + 1
  end

  resetLane(playerLane)
  resetLane(aiLane)
  setDashIndicatorReady(true)
  roundElapsed = 0 -- the difficulty ramp starts over with every round
  nextDotSpawnIn = rollNextDotSpawnIn()
  clearPendingPipeSpawns()
  match.phase = "playing"
  audio.play(swooshingSound)
  refreshOverlay()
end

-- Mirrors the mouse's hold-to-dash timer (see onMouseEvent below) but for
-- the flap key: while holdToDashEnabled, pressing it doesn't flap right
-- away -- it waits to see whether the key comes back up before
-- holdDashDelayMs (a tap, so it flaps on "up") or is still down when the
-- timer fires (a hold, so it dashes instead and the eventual "up" is a
-- no-op). flapKeyHeld guards against OS key-repeat re-arming the timer.
local flapKeyHeld = false
local holdDashKeyTimer = nil
local holdDashSuppressFlapKeyUp = false

local function cancelHoldDashKeyTimer()
  if holdDashKeyTimer then
    timer.cancel(holdDashKeyTimer)
    holdDashKeyTimer = nil
  end
end

local function onKeyEvent(event)
  if event.phase == "up" then
    if event.keyName == keyBindings.flap then
      flapKeyHeld = false
      cancelHoldDashKeyTimer()
      local suppressed = holdDashSuppressFlapKeyUp
      holdDashSuppressFlapKeyUp = false
      if not suppressed and not menuOpen and holdToDashEnabled then
        onFlapInput()
      end
      return true
    end
    return false
  end

  if event.phase ~= "down" then return false end

  if listeningForBinding then
    keyBindings[listeningForBinding] = event.keyName
    saveKeyBindings()
    listeningForBinding = nil
    refreshKeybindLabels()
    return true
  end

  if menuOpen then
    return true -- swallow gameplay keys while the menu is open
  end

  if event.keyName == keyBindings.flap then
    if not holdToDashEnabled then
      onFlapInput()
      return true
    end
    if not flapKeyHeld then
      flapKeyHeld = true
      cancelHoldDashKeyTimer()
      holdDashKeyTimer = timer.performWithDelay(holdDashDelayMs, function()
        holdDashKeyTimer = nil
        if tryDash() then
          holdDashSuppressFlapKeyUp = true
        end
      end)
    end
    return true
  end
  if event.keyName == keyBindings.dash1 or event.keyName == keyBindings.dash2 then
    tryDash()
    return true
  end
  return false
end
Runtime:addEventListener("key", onKeyEvent)

-- ---------- Right-click dash ----------
-- A phone has no right-click and no Z key, and hold-to-dash is off by
-- default, so without a tappable control the dash is simply unreachable
-- there. This is that control: a finger-sized target sitting *behind* the
-- indicator and its label, both of which have no listeners of their own, so
-- a tap anywhere on the cluster falls through to the one handler here. It is
-- created after the tapCatcher, so it takes the tap rather than flapping.
-- Sized against the visible content width (a portrait phone shows far fewer
-- content units than a 16:9 window) and floored at something a thumb can
-- actually hit.
local DASH_BUTTON_SIZE = math.max(56, math.min(78, display.actualContentWidth * 0.17))
local dashButton = display.newRoundedRect(SCREEN_LEFT + 40, SCREEN_TOP + 82, DASH_BUTTON_SIZE, DASH_BUTTON_SIZE, 12)
dashButton:setFillColor(1, 1, 1, 0.07)
dashButton:setStrokeColor(1, 1, 1, 0.22)
dashButton.strokeWidth = 1
dashButton.isHitTestable = true

-- The dash fires from "touch" (on press), not "tap": returning true here to
-- stop the press also reaching the tapCatcher underneath -- which would arm
-- its hold timer, fire a second dash and leave holdDashSuppressTap set,
-- eating the next genuine flap -- also stops Corona synthesising a "tap" for
-- this object, so a tap listener alone would never run. The "tap" listener
-- below stays as a fallback for any path that delivers a tap without a
-- touch; the dash cooldown makes the duplicate call a no-op.
dashButton:addEventListener("touch", function(event)
  if event.phase == "began" and not menuOpen then
    tryDash()
  end
  return true
end)

dashButton:addEventListener("tap", function()
  if menuOpen then return true end
  tryDash()
  return true
end)

local dashIndicator = display.newCircle(SCREEN_LEFT + 40, SCREEN_TOP + 74, 9)
dashIndicator:setFillColor(0.25, 0.85, 0.3)
dashIndicator:setStrokeColor(0, 0, 0, 0.6)
dashIndicator.strokeWidth = 2

local dashIndicatorLabel = display.newText({ text = "DASH", x = dashIndicator.x, y = dashIndicator.y + 20, font = "Assets/troika.otf", fontSize = 10 })
dashIndicatorLabel:setFillColor(0.85, 0.85, 0.85)

setDashIndicatorReady = function(ready)
  dashIndicator.alpha = 1 -- in case a round boundary landed mid-blink
  if ready then
    dashIndicator:setFillColor(0.25, 0.85, 0.3)
  else
    dashIndicator:setFillColor(0.4, 0.4, 0.4)
  end
end

-- Flashes the indicator a few times right as the cooldown finishes, so the
-- moment the dash becomes available again is obvious rather than just a
-- static color change you might not notice.
local function blinkDashIndicator()
  setDashIndicatorReady(true)
  local blinksLeft = 6
  local function step()
    dashIndicator.alpha = (dashIndicator.alpha < 1) and 1 or 0.15
    blinksLeft = blinksLeft - 1
    if blinksLeft > 0 then
      timer.performWithDelay(80, step)
    else
      dashIndicator.alpha = 1
    end
  end
  step()
end

-- A handful of thin streak rects near the bird, parented into the player's
-- own lane group so they're clipped to it the same as everything else,
-- kicked backward and faded/stretched out to read as a gust of wind.
local function spawnDashWind()
  local birdScreenX = laneDisplayX(playerLane, BIRD_LOCAL_X)
  local birdY = playerLane.bird.y

  for _ = 1, 7 do
    local streak = display.newRect(
      playerLane.group,
      birdScreenX - 6 - math.random(0, 14),
      birdY + math.random(-26, 26),
      math.random(20, 36),
      math.random(2, 3)
    )
    streak:setFillColor(1, 1, 1, 0.35 + math.random() * 0.4)
    streak.rotation = math.random(-10, 10)

    local travel = 55 + math.random(0, 35)
    transition.to(streak, {
      time = 320 + math.random(0, 160),
      delay = math.random(0, 90),
      x = streak.x - travel,
      xScale = 1.8,
      alpha = 0,
      onComplete = function(obj)
        if obj.removeSelf then obj:removeSelf() end
      end,
    })
  end
end

-- Returns true if a dash actually fired, false if it was blocked (menu
-- open, not playing, dead, or still on cooldown) -- callers that need to
-- react only to a real dash (e.g. hold-to-dash deciding whether to swallow
-- the eventual release tap) check this instead of assuming it always fires.
tryDash = function()
  if menuOpen then return false end
  if match.phase ~= "playing" then return false end
  if not playerLane.alive then return false end
  if playerLane.dashCooldownRemaining > 0 then return false end

  -- the world advances under the bird, permanently, instead of the bird
  -- lunging out and snapping back: updateLane spends this down as extra
  -- scroll speed over DASH_TRANSITION_TIME, so it plays out as a quick
  -- burst rather than an instant jump, with nothing given back afterward.
  playerLane.dashRemaining = playerLane.dashRemaining + DASH_DISTANCE
  playerLane.dashCooldownRemaining = DASH_COOLDOWN
  setDashIndicatorReady(false)
  audio.play(swooshingSound)
  spawnDashWind()
  ignoreTapUntil = system.getTimer() + 60
  return true
end

-- Running timer waiting to see if a left click held down for
-- holdDashDelayMs should turn into a dash; cancelled on release (or a
-- fresh press) so a quick click still just flaps as normal.
local holdDashTimer = nil

local function cancelHoldDashTimer()
  if holdDashTimer then
    timer.cancel(holdDashTimer)
    holdDashTimer = nil
  end
end

local function onMouseEvent(event)
  if event.type == "down" and event.isSecondaryButtonDown then
    tryDash()
    return true
  end

  if event.type == "down" and event.isPrimaryButtonDown and not event.isSecondaryButtonDown then
    cancelHoldDashTimer()
    holdDashSuppressTap = false -- as above: don't carry one press's flag into the next
    if holdToDashEnabled and not menuOpen then
      holdDashTimer = timer.performWithDelay(holdDashDelayMs, function()
        holdDashTimer = nil
        if tryDash() then
          holdDashSuppressTap = true
        end
      end)
    end
    return false
  end

  if event.type == "up" then
    cancelHoldDashTimer()
  end
  return false
end
Runtime:addEventListener("mouse", onMouseEvent)

-- ---------- Keybind settings menu ----------
-- A small always-visible "KEYS" button that opens a panel of the 3
-- rebindable actions (flap, and the dash's two keys). Tapping a row's
-- CHANGE button puts onKeyEvent into "listening" mode (see
-- listeningForBinding above) so the very next key pressed anywhere becomes
-- that binding. Built last so it renders on top of everything else, same
-- as the theme button.
local keybindButton = display.newRect(screenCenterX, SCREEN_TOP + 20, 70, 28)
keybindButton:setFillColor(0.12, 0.12, 0.12, 0.85)
keybindButton:setStrokeColor(1, 1, 1, 0.5)
keybindButton.strokeWidth = 1
keybindButton.isHitTestable = true

local keybindButtonLabel = display.newText({ text = "KEYS", x = keybindButton.x, y = keybindButton.y, font = "Assets/troika.otf", fontSize = 14 })
keybindButtonLabel:setFillColor(1, 1, 1)

local keybindMenuGroup = display.newGroup()
keybindMenuGroup.isVisible = false

local keybindBackdrop = display.newRect(keybindMenuGroup, screenCenterX, screenCenterY, 460, 430)
keybindBackdrop:setFillColor(0.05, 0.05, 0.05, 0.93)
keybindBackdrop:setStrokeColor(1, 1, 1, 0.4)
keybindBackdrop.strokeWidth = 2

local keybindTitle = display.newText({ parent = keybindMenuGroup, text = "KEY BINDINGS", x = screenCenterX, y = screenCenterY - 105, font = "Assets/troika.otf", fontSize = 22 })
keybindTitle:setFillColor(1, 1, 1)

local keybindHint = display.newText({ parent = keybindMenuGroup, text = "", x = screenCenterX, y = screenCenterY + 150, width = 400, font = "Assets/troika.otf", fontSize = 13, align = "center" })
keybindHint:setFillColor(1, 0.85, 0.25)

local keybindValueTexts = {} -- binding key ("flap"/"dash1"/"dash2") -> its value display text object

local BINDING_ROWS = {
  { key = "flap", label = "FLAP", y = screenCenterY - 55 },
  { key = "dash1", label = "DASH 1", y = screenCenterY - 10 },
  { key = "dash2", label = "DASH 2", y = screenCenterY + 35 },
}

for _, row in ipairs(BINDING_ROWS) do
  local actionText = display.newText({ parent = keybindMenuGroup, text = row.label, x = screenCenterX - 160, y = row.y, font = "Assets/troika.otf", fontSize = 16 })
  actionText.anchorX = 0
  actionText:setFillColor(0.85, 0.85, 0.85)

  local valueText = display.newText({ parent = keybindMenuGroup, text = string.upper(keyBindings[row.key]), x = screenCenterX + 10, y = row.y, font = "Assets/troika.otf", fontSize = 16 })
  valueText:setFillColor(1, 0.85, 0.25)
  keybindValueTexts[row.key] = valueText

  local changeButton = display.newRect(keybindMenuGroup, screenCenterX + 150, row.y, 90, 30)
  changeButton:setFillColor(0.2, 0.2, 0.2)
  changeButton:setStrokeColor(1, 1, 1, 0.4)
  changeButton.strokeWidth = 1
  changeButton.isHitTestable = true

  local changeLabel = display.newText({ parent = keybindMenuGroup, text = "CHANGE", x = changeButton.x, y = changeButton.y, font = "Assets/troika.otf", fontSize = 12 })
  changeLabel:setFillColor(1, 1, 1)

  changeButton:addEventListener("tap", function()
    listeningForBinding = row.key
    keybindHint.text = "PRESS A KEY FOR " .. row.label .. "..."
    return true
  end)
end

-- "Hold to dash" checkbox: holding the flap input (left click or the flap
-- key) down for holdDashDelayMs then fires a dash instead of that input
-- just flapping, handled by the hold timers in onMouseEvent and onKeyEvent.
local holdToDashCheckboxX = screenCenterX - 160 + 9
local holdToDashRowY = screenCenterY + 68

local holdToDashCheckbox = display.newRect(keybindMenuGroup, holdToDashCheckboxX, holdToDashRowY, 18, 18)
holdToDashCheckbox:setStrokeColor(1, 1, 1, 0.6)
holdToDashCheckbox.strokeWidth = 1
holdToDashCheckbox.isHitTestable = true

local holdToDashCheckmark = display.newText({ parent = keybindMenuGroup, text = "X", x = holdToDashCheckboxX, y = holdToDashRowY - 1, font = "Assets/troika.otf", fontSize = 13 })
holdToDashCheckmark:setFillColor(0.25, 0.85, 0.3)

local holdToDashLabel = display.newText({ parent = keybindMenuGroup, text = "HOLD TO DASH", x = holdToDashCheckboxX + 18, y = holdToDashRowY, font = "Assets/troika.otf", fontSize = 14 })
holdToDashLabel.anchorX = 0
holdToDashLabel:setFillColor(0.85, 0.85, 0.85)
holdToDashLabel.isHitTestable = true

local function refreshHoldToDashCheckbox()
  if holdToDashEnabled then
    holdToDashCheckbox:setFillColor(0.15, 0.3, 0.15)
  else
    holdToDashCheckbox:setFillColor(0.12, 0.12, 0.12)
  end
  holdToDashCheckmark.isVisible = holdToDashEnabled
end
refreshHoldToDashCheckbox()

local function toggleHoldToDash()
  holdToDashEnabled = not holdToDashEnabled
  saveKeyBindings()
  refreshHoldToDashCheckbox()
end
holdToDashCheckbox:addEventListener("tap", function()
  toggleHoldToDash()
  return true
end)
holdToDashLabel:addEventListener("tap", function()
  toggleHoldToDash()
  return true
end)

-- Hold-delay slider: drags between HOLD_DASH_DELAY_MIN_MS and
-- HOLD_DASH_DELAY_MAX_MS, snapped to the nearest 10ms. Works from either
-- the handle or a tap/drag anywhere on the track, via Solar2D's "touch"
-- event (fired for mouse drags too, same as everything else in this menu).
local SLIDER_TRACK_LEFT_X = screenCenterX - 160
local SLIDER_TRACK_RIGHT_X = screenCenterX + 160
local SLIDER_TRACK_WIDTH = SLIDER_TRACK_RIGHT_X - SLIDER_TRACK_LEFT_X
local holdDashDelayRowY = screenCenterY + 100
local holdDashDelayTrackY = screenCenterY + 122

local holdDashDelayLabel = display.newText({ parent = keybindMenuGroup, text = "HOLD DELAY", x = SLIDER_TRACK_LEFT_X, y = holdDashDelayRowY, font = "Assets/troika.otf", fontSize = 14 })
holdDashDelayLabel.anchorX = 0
holdDashDelayLabel:setFillColor(0.85, 0.85, 0.85)

local holdDashDelayValueText = display.newText({ parent = keybindMenuGroup, text = "", x = SLIDER_TRACK_RIGHT_X, y = holdDashDelayRowY, font = "Assets/troika.otf", fontSize = 14 })
holdDashDelayValueText.anchorX = 1
holdDashDelayValueText:setFillColor(1, 0.85, 0.25)

local holdDashDelayTrack = display.newRect(keybindMenuGroup, screenCenterX, holdDashDelayTrackY, SLIDER_TRACK_WIDTH, 6)
holdDashDelayTrack:setFillColor(0.25, 0.25, 0.25)
holdDashDelayTrack:setStrokeColor(1, 1, 1, 0.3)
holdDashDelayTrack.strokeWidth = 1
holdDashDelayTrack.isHitTestable = true

local holdDashDelayHandle = display.newCircle(keybindMenuGroup, SLIDER_TRACK_LEFT_X, holdDashDelayTrackY, 9)
holdDashDelayHandle:setFillColor(1, 0.85, 0.25)
holdDashDelayHandle:setStrokeColor(0, 0, 0, 0.6)
holdDashDelayHandle.strokeWidth = 1
holdDashDelayHandle.isHitTestable = true

local function refreshHoldDashDelayUI()
  local fraction = (holdDashDelayMs - HOLD_DASH_DELAY_MIN_MS) / (HOLD_DASH_DELAY_MAX_MS - HOLD_DASH_DELAY_MIN_MS)
  holdDashDelayHandle.x = SLIDER_TRACK_LEFT_X + fraction * SLIDER_TRACK_WIDTH
  holdDashDelayValueText.text = string.format("%.2fs", holdDashDelayMs / 1000)
end
refreshHoldDashDelayUI()

local function setHoldDashDelayFromX(x)
  local clampedX = math.max(SLIDER_TRACK_LEFT_X, math.min(SLIDER_TRACK_RIGHT_X, x))
  local fraction = (clampedX - SLIDER_TRACK_LEFT_X) / SLIDER_TRACK_WIDTH
  local ms = HOLD_DASH_DELAY_MIN_MS + fraction * (HOLD_DASH_DELAY_MAX_MS - HOLD_DASH_DELAY_MIN_MS)
  ms = math.floor(ms / 10 + 0.5) * 10
  holdDashDelayMs = math.max(HOLD_DASH_DELAY_MIN_MS, math.min(HOLD_DASH_DELAY_MAX_MS, ms))
  refreshHoldDashDelayUI()
end

local function onHoldDashDelayTouch(event)
  if event.phase == "began" then
    display.getCurrentStage():setFocus(event.target, event.id)
    event.target.isFocus = true
    setHoldDashDelayFromX(event.x)
  elseif event.target.isFocus then
    if event.phase == "moved" then
      setHoldDashDelayFromX(event.x)
    elseif event.phase == "ended" or event.phase == "cancelled" then
      display.getCurrentStage():setFocus(nil, event.id)
      event.target.isFocus = false
      saveKeyBindings()
    end
  end
  return true
end
holdDashDelayHandle:addEventListener("touch", onHoldDashDelayTouch)
holdDashDelayTrack:addEventListener("touch", onHoldDashDelayTouch)

local keybindCloseButton = display.newRect(keybindMenuGroup, screenCenterX, screenCenterY + 185, 120, 34)
keybindCloseButton:setFillColor(0.3, 0.05, 0.05)
keybindCloseButton:setStrokeColor(1, 1, 1, 0.4)
keybindCloseButton.strokeWidth = 1
keybindCloseButton.isHitTestable = true

local keybindCloseLabel = display.newText({ parent = keybindMenuGroup, text = "CLOSE", x = keybindCloseButton.x, y = keybindCloseButton.y, font = "Assets/troika.otf", fontSize = 15 })
keybindCloseLabel:setFillColor(1, 1, 1)

local function closeKeybindMenu()
  menuOpen = false
  listeningForBinding = nil
  keybindHint.text = ""
  keybindMenuGroup.isVisible = false
end
keybindCloseButton:addEventListener("tap", function()
  closeKeybindMenu()
  return true
end)

keybindButton:addEventListener("tap", function()
  menuOpen = true
  keybindHint.text = ""
  keybindMenuGroup.isVisible = true
  return true
end)

refreshKeybindLabels = function()
  for key, valueText in pairs(keybindValueTexts) do
    valueText.text = string.upper(keyBindings[key])
  end
  keybindHint.text = ""
end

-- ---------- Round bookkeeping ----------
-- Finalizes the round: totals both lanes' scores as they stand at the moment
-- of the crash and moves on to the round/match summary. Under the
-- elimination rule this is called from exactly one place -- the tick on
-- which either bird goes down -- rather than from a spectate/skip path.
finishRound = function()
  match.playerTotal = match.playerTotal + playerLane.score
  match.aiTotal = match.aiTotal + aiLane.score

  -- Both can go down on the same tick: the AI's handicap roll fires while
  -- updateLane is scoring its pipe, which is the same tick the player may
  -- hit something, so "both" is a real outcome and not just a tidy default.
  if not playerLane.alive and not aiLane.alive then
    match.eliminated = "both"
  elseif not playerLane.alive then
    match.eliminated = "you"
  else
    match.eliminated = "ai"
  end

  if match.round >= TOTAL_ROUNDS then
    match.phase = "matchover"
    if match.playerTotal > match.bestTotal then
      match.bestTotal = match.playerTotal
      saveBestTotal()
      bestLabel.text = "BEST " .. match.bestTotal
    end
  else
    match.phase = "roundover"
  end
  refreshOverlay()
end

-- ---------- Main loop ----------
local function gameLoop()
  if menuOpen then return end -- freeze the action while the keybind menu is open
  -- Nothing ticks outside a live round: the payoff/flight pass below is part
  -- of the action too, so it stops with the rest of it rather than bouncing
  -- coins across a finished round's overlay and dropping pipes into two
  -- frozen lanes. Whatever is still queued is destroyed by
  -- clearPendingPipeSpawns when the next round starts.
  if match.phase ~= "playing" then return end

  roundElapsed = roundElapsed + TICK_DT

  nextDotSpawnIn = nextDotSpawnIn - TICK_DT
  if nextDotSpawnIn <= 0 then
    nextDotSpawnIn = rollNextDotSpawnIn()
    local targetLane = (math.random() < 0.5) and playerLane or aiLane
    if targetLane.alive then
      spawnDot(targetLane)
    end
  end

  local dashWasOnCooldown = playerLane.dashCooldownRemaining > 0
  updateLane(playerLane, TICK_DT)
  if dashWasOnCooldown and playerLane.dashCooldownRemaining <= 0 then
    blinkDashIndicator()
  end

  if aiLane.alive then
    updateAI(aiLane, TICK_DT)
  end
  updateLane(aiLane, TICK_DT)

  -- Elimination: the first crash ends the round for BOTH lanes. Leaving
  -- "playing" is what stops them -- nothing calls updateLane outside this
  -- branch any more -- so the survivor freezes exactly where it was
  -- instead of flying on alone.
  if not playerLane.alive or not aiLane.alive then
    finishRound()
    return
  end

  -- Delayed coin payoffs: the collected coin bounces across to the opposing
  -- lane over COIN_PIPE_DELAY, and the pipe is generated at the moment it
  -- lands. Walked back-to-front so a payoff can be dropped as it fires.
  for i = #pendingPipeSpawns, 1, -1 do
    local pending = pendingPipeSpawns[i]
    if not pending.flight then
      beginCoinFlight(pending) -- first tick this payoff has been seen
    end
    pending.remaining = pending.remaining - TICK_DT
    updateCoinFlight(pending.flight, 1 - math.max(0, pending.remaining) / COIN_PIPE_DELAY)
    if pending.remaining <= 0 then
      endCoinFlight(pending)
      spawnPipe(otherLane(pending.from))
      table.remove(pendingPipeSpawns, i)
    end
  end
end

local gameLoopTimer = timer.performWithDelay(25, gameLoop, 0)

end -- main()

-- The layout is built exactly once, from display.actualContentWidth/Height,
-- and nothing repositions afterwards -- so those have to be the *settled*
-- values. Deferring one frame (what this used to do) is enough on desktop,
-- but not in a mobile browser: the canvas there was measured stepping
-- 300x150 -> 412x618 -> 412x880 across the first second, and laying out
-- against the middle reading puts the real left edge ~86px inside where the
-- game thinks it is. The lanes still look about right, but everything
-- anchored to SCREEN_LEFT -- the BEST label, and the dash control -- slides
-- off the screen, which is what made the dash unreachable on a phone.
--
-- So poll until the size stops changing before building anything, with a
-- hard cap so a pathological resize loop can still boot the game.
local LAYOUT_POLL_MS = 50
local LAYOUT_STABLE_SAMPLES = 3 -- consecutive identical readings
-- Stability alone isn't enough: the canvas sits at its 300x150 default for
-- the first few hundred milliseconds, which reads as perfectly stable and
-- would boot the layout against the placeholder -- the very thing this is
-- meant to avoid. So don't accept any reading before this floor.
local LAYOUT_MIN_WAIT_MS = 400
local LAYOUT_MAX_WAIT_MS = 3000

local lastW, lastH, stableCount, waited = nil, nil, 0, 0
local layoutWaitTimer
layoutWaitTimer = timer.performWithDelay(LAYOUT_POLL_MS, function()
  local w, h = display.actualContentWidth, display.actualContentHeight
  if w == lastW and h == lastH then
    stableCount = stableCount + 1
  else
    stableCount, lastW, lastH = 0, w, h
  end
  waited = waited + LAYOUT_POLL_MS

  local settled = stableCount >= LAYOUT_STABLE_SAMPLES and waited >= LAYOUT_MIN_WAIT_MS
  if settled or waited >= LAYOUT_MAX_WAIT_MS then
    timer.cancel(layoutWaitTimer)
    main()
  end
end, 0)
